### ISSUE TITLE
Simple code example downloads empty PDF file

### ISSUE THREAD

**Issue by alundiak** [eKoopmans/html2pdf#1]
FYI @eKoopmans - core issue in `jsPDF` - https://github.com/MrRio/jsPDF/issues/1220

My HTML 

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.debug.js"></script>
    <script src="lib/html2canvas.min.js"></script>
    <script src="lib/html2pdf.js"></script>
</head>
<body>
    <div id="element-to-print">
        Hello People
    </div>
    <script type="text/javascript" src="./index.js"></script>
</body>
</html>
```

My JS:

```js
var element = document.getElementById('element-to-print');
const options = {
    margin: 10,
    filename: pdfFileName,
    image: {
        type: 'jpeg',
        quality: 0.98
    },
    html2canvas: {
        dpi: 192,
        letterRendering: true
    },
    jsPDF: {
        unit: 'in',
        format: 'letter',
        orientation: 'portrait'
    }
}

html2pdf(element, options);
```

Above code setup give same "white paged aka empty" PDF file.

If I do comment `unit/format` lines, all works good.

**Comment by eKoopmans** [comment]
Hi @alundiak, I've made a jsFiddle of your issue [here](https://jsfiddle.net/7xLza7ss/).

Here's the problem: you've set `margin: 10` and `unit: 'in'`. That means your margin is 10 inches, which is larger than the page (when applied to left, right, top, and bottom). So nothing shows up on the page. Try changing to `margin: 1` and see the result.

Your issue over at jsPDF has the same problem, I'll comment about that there.

**Comment by alundiak** [comment]
@eKoopmans indeed u r right. I kinda get used to pixels by default, so I was in fast mode copied code from your readme, and just modified margin. Totally did not think that it's in inches. Thanks. resolved - pdf downloaded correctly.

In regards to jsPDF - examples by default suggest using 10, so I used :) u know - KISS - so I did it.
