### ISSUE TITLE
Graph not showing in pdf

### ISSUE THREAD

**Issue by adeel3612** [eKoopmans/html2pdf#10]
hello @eKoopmans  I used your library and no doubt i have to accept this is the best thing for generating pdf and resolve so many problems of mine code with just 4 5 lines. One thing is giving me a problem which i think missing on my side. When i was using just html2canvas along with jsPDF to generate there were many problems but the chart was printing now after using your library, Chart which is producing in a canvas by Chartjs library it is not printing on pdf. Any solution? this is what i am doing. 

`var element = document.getElementById('main_data_div');
html2pdf(element, {
        margin:       0,
        filename:     'myfile.pdf',
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { dpi: 192, letterRendering: true },
        jsPDF:        { unit: 'in', format: 'a4', orientation: 'l' }
    });`

There is canvas element in my ` main_data_div`

**Comment by eKoopmans** [comment]
Hi @adeel3612, I believe what you've described is a problem with offscreen rendering. It's a known issue in html2canvas, I have submitted a [pull request](https://github.com/niklasvh/html2canvas/pull/1083) to try to resolve the problem, but it hasn't been accepted yet.

That is why, for html2pdf, I have provided [custom builds](https://github.com/eKoopmans/html2pdf/tree/master/vendor) of the dependencies. I recommend using the version of html2canvas you find there, for now. You'll notice in [the readme](https://github.com/eKoopmans/html2pdf#install) that the order you include the dependencies is important - you must include jsPDF first, then the custom build of html2canvas, *then* html2pdf.

You can see #2 for more discussion about the "black boxes", it should be resolved by using the custom html2canvas build.

**Comment by eKoopmans** [comment]
Sorry, it sounds like you resolved the "black box" problem and this is a separate issue. I'm not familiar with Chartjs, but it would help if you could create a [jsFiddle](https://jsfiddle.net/o0kL8zkk/) that illustrates the problem - open that link and create a fork, it has the dependencies (jsPDF, html2canvas, and html2pdf) already loaded.

**Comment by adeel3612** [comment]
hey @eKoopmans  yeah blackbox was solved but i dont know why chart is not printing in pdf. jsfiddle always was a headache for me but i am trying. Let me change it

**Comment by adeel3612** [comment]
@eKoopmans  sorry for late reply here is my [jsfiddle link](https://jsfiddle.net/o0kL8zkk/1/) you can view that this is printing but not the canvas or may be the specifically  graph.

**Comment by adeel3612** [comment]
@eKoopmans any help you can provide? is this problem is on my side or there is bug in html2pdf.

**Comment by eKoopmans** [comment]
Hi @adeel3612 sorry, I haven't been at a computer the past couple days. Might be a day or two more before I can look into this.

**Comment by adeel3612** [comment]
@eKoopmans  no problem mate! i hope we can solve this issue or i have to look another library.

**Comment by eKoopmans** [comment]
Alright, finally got a chance to look at this! Sorry for the wait @adeel3612.

So, I have good news and bad news. The good news: I've [created a solution](https://jsfiddle.net/o0kL8zkk/4/). The bad news: it's a bit of a hack. What I've done is basically swapped out the Chart.js canvas with an image right before calling html2pdf, then swapping the canvas back in when it's done. Here's the details of the changes I made:

1. Removed an extra `</div>` in your HTML that was causing the canvas to be outside of `main_data_div` anyway.
2. Created `replaceGraphs()` and `fixGraphs()` to replace each graph with an image, and later swap the graphs back in.
2. In `generate_pdf`, called `replaceGraphs()` before generating the PDF, and used html2canvas' `onrendered` callback to swap the graphs back in.

**Comment by adeel3612** [comment]
@eKoopmans Sorry for late reply due to weekend. Let me look into this. Thankx for your help.

**Comment by adeel3612** [comment]
@eKoopmans Hello Sir! Thank you for your help in this issue. I have got much help from you. No doubt you are doing great to the open source community. I tried your solution and it worked can you plz tell me what was the problem. Actually i did not understand what was the issue in this regard. and what you have applied to solve this.

**Comment by adeel3612** [comment]
@eKoopmans hello again sorry to bother you again i have a question that on pdf graph elements are little blurry is there any solution to solve this ?

**Comment by eKoopmans** [comment]
Hi @adeel3612! To answer your questions:

1. The fix I shared earlier was a "hack" - it worked, but it didn't solve the underlying problem. Today I found the bug in `html2pdf` that was causing *all* canvases to not render properly. I've fixed that bug, now you can use Chart.js without having to change anything. [This fiddle](https://jsfiddle.net/o0kL8zkk/6/) shows it working - the only change I made to your original code was to remove the extra `</div>` in the HTML code.

2. I don't think there's anything I can do to fix the blurry graphs, unfortunately. For everything else, you can use the `dpi` option on `html2canvas` to increase the resolution and make things less blurry, but that won't improve the resolution of embedded canvases.

So canvases are now working - thanks for finding the problem! Try out the latest version of `html2pdf` and see if it solves your issue!

**Comment by adeel3612** [comment]
Hi @eKoopmans Thanks sir! Thank you very much for your help in this regard. cheers!

**Comment by eKoopmans** [comment]
@adeel3612 I found a solution to reduce the blurriness of your canvases! You can change [`window.devicePixelRatio`](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) before drawing on your canvas. [Here's a fiddle](https://jsfiddle.net/o0kL8zkk/7/) with just one line of code added:

```
window.devicePixelRatio = 2;
```

Support for the feature is relatively new (IE11+), but it should improve things on any browser that supports it. I'm going to see about adding it into html2canvas directly, if I can then you won't need to do anything to your code.

**Comment by eKoopmans** [comment]
Okay, I can't incorporate the change directly into html2canvas, it has to be set before the canvas is drawn. In any case, set that before you start drawing your canvases and you should be good! I'd also recommend resetting `devicePixelRatio` after drawing your canvases - something like this:

```js
var scale = 2;
window.devicePixelRatio *= scale;
new_chart = new Chart(ctx, {
    type: 'line',
    data: data,
    options: options
});
window.devicePixelRatio /= scale;
```

**Comment by adeel3612** [comment]
@eKoopmans Thank you for your help! i am checking this. I want to know why resetting of PixelRation should be done?

**Comment by eKoopmans** [comment]
`window.devicePixelRatio` is automatically set by the browser based on the user's device (i.e. Apple "Retina" displays that have double pixel density), so I figure it's safest to reset the value when you're done with it.

In terms of canvases, what seems to matter is the value of `window.devicePixelRatio` when you draw on the canvas - if you change the pixel ratio afterwards, the canvas still remains higher-resolution.

This is only with my limited testing in Windows Chrome, so if you find that this isn't a universal fix, let me know. For me when I use the fiddle (and/or the code above that resets the ratio afterwards), I get a much less blurry graph in the PDF.

**Comment by adeel3612** [comment]
yeah i have used it in the chrome. Let me try in the other browsers and i will let you know about the result.

**Comment by hestacio** [comment]
@eKoopmans dude, you are the best.  I was spending all day trying to figure out why my pdf isn't rendering the bottom part of my last page.  I used your custom html2canvas.  Thanks man..saved me alot of headache!

Quick suggestion, maybe for the newbie reactjs devs.  In your documentation, mention that it has to be className instead of just "class" when they want to do those divs with the pagebreaks.

**Comment by eKoopmans** [comment]
No worries, and thanks for the tip @hestacio! I added a note in the readme.

**Comment by eKoopmans** [comment]
Closing - original issue resolved [here](https://github.com/eKoopmans/html2pdf/issues/10#issuecomment-303902563), further discussion was about reducing blurriness of canvas elements, resolved [here](https://github.com/eKoopmans/html2pdf/issues/10#issuecomment-304415946).
