### ISSUE TITLE
Break Page, Dynamic Pages

### ISSUE THREAD

**Issue by ViniciosPsidonik** [eKoopmans/html2pdf#108]
Hi, I've been trying to find a way to insert the 'break pager', to dynamic pages, always in the end of the page, but I did not succeed... someone had found a way of doing that ? Please help me, I don't know what do anymore..

**Comment by sh-tomer** [comment]
+1

**Comment by shayl29** [comment]
+1

**Comment by Greensahil** [comment]
I fixed this my breaking my responsivenss for a few seconds using
$('meta[name="viewport"]').prop('content', 'width=1440');
and then refreshing the page using jquery

**Comment by eKoopmans** [comment]
Hi, closing as resolved by the v0.9.1 page-break features.
