### ISSUE TITLE
Canvas cropped when using rotate image

### ISSUE THREAD

**Issue by amine86** [eKoopmans/html2pdf#11]
Hello,

  Thank you very much for this project,
   I want to know if we can have a selectable text in the PDF file ? ( as my test I got only a jpeg image under a PDF file).
   Also I noticed a bug when testing, when I use a rotate image, it's cropped from the bottom and right and not positionned correctly,  please see the attached file, (Preview from browser and the final result with pdf)

[myfile-2.pdf](https://github.com/eKoopmans/html2pdf/files/1036876/myfile-2.pdf)

![preview_from_html](https://cloud.githubusercontent.com/assets/29050869/26563274/35e0b07e-44bf-11e7-8d6a-17844238fbf3.png)

Thank you very much,

**Comment by eKoopmans** [comment]
Hi @amine86, you're welcome! To answer your questions:

1. No selectable text unfortunately, this package relies purely on turning the HTML into an image before going to PDF.

2. I'll be happy to investigate your rotation issues. Would you please provide some example code? It would be easiest for me if you would please fork [this jsFiddle](https://jsfiddle.net/rL41y062/), which has the dependencies already loaded, and add code there to show the rotation issue. Thanks!

**Comment by amine86** [comment]
Hi @eKoopmans , thank you very much for your reply,

 This is a fast example : https://jsfiddle.net/yynmre4k/

Thanks for your helps,

**Comment by amine86** [comment]
Hi @eKoopmans 

    any news about this issue ?

**Comment by eKoopmans** [comment]
Yes, thanks for waiting @amine86. It's a problem directly in html2canvas, not html2pdf itself, so I'm going to move this conversation there to your issue at niklasvh/html2canvas#1138.
