### ISSUE TITLE
pdf-callback branch about

### ISSUE THREAD

**Issue by mesutgok** [eKoopmans/html2pdf#110]
hi,

pdf-callback branch when to merge master ? 

i need event list (success, fail) pdf generation.

**Comment by foria** [comment]
+1

**Comment by eKoopmans** [comment]
Hi @mesutgok @foria, the pdf-callback branch is obsolete, it was replaced with the "new API" of v0.9.0 in May 2018. You can now get feedback of when the process is done like so:

```js
html2pdf().from(element).save().then(function () {
    // Whatever you want to happen when it's done!
});
// Or even:
// html2pdf(element).then(function () { ... });
```
