### ISSUE TITLE
cannot dynamically render the pdf generated using html2pdf function

### ISSUE THREAD

**Issue by dilagurung** [eKoopmans/html2pdf#120]
I don't know whether it's an issue or feature which is required. But basically, I am looking for a function which returns the pdf created by htmltopdf function and render it dynamically rather than downloading it.

**Comment by lulul62** [comment]
Iam lookin for this too..

**Comment by dilagurung** [comment]
@lulul62 
Thing is, you need to do bit modification in html2pdf.js. 

Add the following lines.

![image](https://user-images.githubusercontent.com/10268944/41797797-1b5313d8-768b-11e8-99c7-834464bc4ad3.png)
Consider Line number 391 to 404 (refer to image attachment)

Let me know if that help.
