### ISSUE TITLE
problem with html2pdf, jsPDF and angular5

### ISSUE THREAD

**Issue by djanesch** [eKoopmans/html2pdf#127]
@eKoopmans i have troubles getting html2pdf running with jsPDF in angular5.
so far i have done following steps:

- [X] - npm install jspdf --save
- [X] - npm install @types/jspdf --save
- [X] - npm install --save html2pdf.js
- [X] - Add following in angular-cli.json: "scripts": [ "../node_modules/jspdf/dist/jspdf.min.js" ]
- [X] - import scripts it in my component:
import * as jsPDF from 'jspdf';
import html2pdf from 'html2pdf.js';

the code where i want to create pdf looks like:
```
    const pdf = new jsPDF('p', 'pt', 'letter');
    html2pdf(this.document.body, pdf, function(pdfOut) {
      pdfOut.save('Test.pdf');
    });
```

maybe you could give me a clue whats wrong.
if i run the application i get the following error:

> html2pdf_js_1.default is not a function

**Comment by sameerpallav** [comment]
Have you tried the html2pdf.bundle.js?

1. Add following in angular-cli.json: "scripts": [ "../path/to//html2pdf.bundle.min.js" ] (can skip this if next two steps works)
2. declare var html2pdf: any;
`
		const element = ele.nativeElement;
		const opt = {
			margin:       0,
			filename:     filename,
			image:        { type: 'jpeg', quality: 1 },
			html2canvas:  { scale: 3,
				letterRendering: true,
				useCORS: true},
			jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait', pagesplit: true}
		};

		// New Promise-based usage:
		const worker = html2pdf().from(element).set(opt).save()
			.then(done => {
				this.loader = false;
			});`

**Comment by djanesch** [comment]
@sameerpallav thanks for your code. seems to work perfectly. 1 step with adding to angular-cli.json was not needed in my case.
