### ISSUE TITLE
Upgrade to jsPDF to 1.4 (webpack production builds fail)

### ISSUE THREAD

**Issue by nicholaai** [eKoopmans/html2pdf#130]
hey guys. can we get this package to upgrade it's jsPDF dependency to jsPDF v 1.4? 

I intend to use this client side on a static site generated with webpack. The package works well in development. When I try create a production bundle the process fails.

Details of this issue are can be found on [this issue](https://github.com/MrRio/jsPDF/issues/1637). They've since updated from 1.3.5 and it should work.

Thanks!

**Comment by chriddell** [comment]
@nicholaai did you manage to create a production bundle successfully? if so, what were the steps you took to fix? 

having this same issue and any help would be much appreciated

**Comment by nicholaai** [comment]
@chriddell yeah. just run `yarn upgrade html2pdf.js`.  That will upgrade jspdf in the process. i was blind and didn't notice the `^` character in the dependencies 

```
"dependencies": {
    "es6-promise": "^4.1.1",
    "html2canvas": "^1.0.0-alpha.12",
    "jspdf": "^1.3.5"
  },
```

i'm using gatsby so i was able to followed the instructions on [this page](https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-code-classlanguage-textwindowcode-is-defined)

```
exports.modifyWebpackConfig = ({ config, stage }) => {
  if (stage === "build-html") {
    config.loader("null", {
      test: /html2pdf/,
      loader: "null-loader",
    })
  }
}
```

 good luck!
