### ISSUE TITLE
Not Working on Firefox

### ISSUE THREAD

**Issue by erwinyusrizal** [eKoopmans/html2pdf#143]
Hi any idea to make this plugin working on FF ? the worker promise always pending

Thanks

**Comment by mathiaswillburger** [comment]
Are you using the `margin` parameter in the html2pdf configuration options by any chance? I had the same issue, that it was not working in Firefox and IE. As soon as I removed the margin option everything worked fine. 

To get the same result with the margin, I moved the margin handling to the CSS style of the html I am passing to the component.

Maybe that helps for you too until this is fixed.

**Comment by erwinyusrizal** [comment]
You're right @mathiaswillburger it's working now thank you

**Comment by Trungks82** [comment]
> Are you using the `margin` parameter in the html2pdf configuration options by any chance? I had the same issue, that it was not working in Firefox and IE. As soon as I removed the margin option everything worked fine.
> 
> To get the same result with the margin, I moved the margin handling to the CSS style of the html I am passing to the component.
> 
> Maybe that helps for you too until this is fixed.

Can you tell me how do I do it?

**Comment by RizTyagi** [comment]
--I removed margin property but still not working.
---Here is my code sample
-- element is my content which goes to convert in pdf
--headerElem is my header if genrated pdf have more than 2 pages it will repeat 
`   var  element =  #document.getElementsByTagName('body')[0];
var headerElem = document.getElementById('i-Header');'
 'const HEADER_HEIGHT = 0;'
'var opt = {
            filename: 'fileName',
            image: { type: 'jpeg', quality: 0.7 },
            html2canvas: { scale: 2, useCORS: true },
            jsPDF: { format: 'a3', unit: 'mm' },
            pagebreak: { before: '.i-pdf--page' },
                    };'
'html2pdf().from(headerElem).toImg().get('img').then(function (img) {   
              html2pdf().from(element).toPdf().get('pdf').then(function (pdf) {
                   var totalPages = pdf.internal.getNumberOfPages();
                                          for (var i = 1; i <= totalPages; i++) {                          
                                              pdf.setPage(i);
                            if (i != 1) {
                                pdf.addImage(img, 'JPEG', 6, 0, pdf.internal.pageSize.getWidth() - 12, HEADER_HEIGHT);
                            }
                            pdf.text(30, pdf.internal.pageSize.getHeight() - 1, getFooterText(i, totalPages));
                        }
});});
//function getFooterText(PageNo, TotalPages) {}
`

**Comment by Ajithkumarparthasarathy** [comment]
We are currently facing an issue with html2pdf: it works fine in Chrome and Edge, but we're encountering problems in Firefox. Below is the code we're using to generate the PDF. It works correctly if the PDF has 23 pages, but fails otherwise.
`html2pdf().from(element).set({
      html2canvas: { dpi: 250, letterRendering: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    }).toPdf().get('pdf').then(function (pdf) {
      var totalPages = pdf.internal.getNumberOfPages();
      var pageWidth = pdf.internal.pageSize.getWidth();
      var pageHeight = pdf.internal.pageSize.getHeight();
      var headerText = "";
      var headerTextWidth = pdf.getStringUnitWidth(headerText) * pdf.internal.getFontSize() / pdf.internal.scaleFactor;
      var headerX = (pageWidth - headerTextWidth) / 2;

      for (var i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        pdf.text(headerText, headerX, 10);
        var pageText = "Page " + i + " of " + totalPages;
        var pageTextWidth = pdf.getStringUnitWidth(pageText) * pdf.internal.getFontSize() / pdf.internal.scaleFactor;
        var pageX = (pageWidth - pageTextWidth) / 2;
        pdf.text(pageText, pageX, pageHeight - 10);
      }`
