### ISSUE TITLE
Dynamic page breaks for a long range table or texts.

### ISSUE THREAD

**Issue by axiom88-guru** [eKoopmans/html2pdf#145]
Hi @eKoopmans, 
Thank you for such a great tool. I am not sure if you already implemented auto page breaks that you mentioned [here](https://github.com/eKoopmans/html2pdf/issues/13#issuecomment-308319719). 

I suspect that the auto-break is not there yet? I've found many discussions for that. But I haven't found an elegant idea. 
Please find the attached screenshot below to see what kind of issue I have faced.
Would you please recommend any good but simple idea? 
Thanks.  
![image](https://user-images.githubusercontent.com/19179511/44640789-72d84a00-a9cc-11e8-9149-ea36b5180102.png)

**Comment by Ljuka** [comment]
I agree with @axiom88-guru - it would be nice if there is a simple way to solve this

**Comment by axiom88-guru** [comment]
@Ljuka  I solved the issue by calculating contents height and inserting page breaks manually.
Here is the link to the reference. 
https://github.com/eKoopmans/html2pdf/issues/83

**Comment by adbahrani** [comment]
@axiom88-guru Which solution on #83 did you end up using ? @lcrojanouninorte  or @lipter

**Comment by axiom88-guru** [comment]
I ended up using @Icrojanouninorte's solution. Hope it helps

```
        // Table 
        const tblRows = tbodyElement && tbodyElement.childNodes;
        if (tblRows) {
            tblRows.forEach((row: any) => {
                if(row.offsetHeight)
                    currentPageHeight = currentPageHeight + row.offsetHeight;
                if (currentPageHeight > maxPageHeight)
                {
                    currentPageHeight = 0;
                    var pageBreak = document.createElement('div');
                    pageBreak.className = 'html2pdf__page-break';
                    row.before(pageBreak);
                }
            });
        }
```

**Comment by abrhbruno** [comment]
For anyone who ends up on this issue (like I did when searching for solutions for my specific issue):
I managed to do this by using a separate page component on Angular to store the separate pages.
This way I inherited all the styles and benefits I had on my full page but broke it into pages with fixed size, with the possibility of  having header and footer too.

Check the details on my answer here #281
