### ISSUE TITLE
Canvas image

### ISSUE THREAD

**Issue by cptolemy** [eKoopmans/html2pdf#149]
Good afternoon,

If I place a canvas in a div, and draw to it, can I save all normally, or must I convert first the canvas svg to an image url? If yes, how do I add it to the whole pdf...?

The div will contain the canvas, tables and texts, which I intend to save as PDF.

Thanks in advance.

Kind regards

**Comment by eKoopmans** [comment]
Hi @cptolemy, the canvases should work with no modification! Let me know if there's any issue - I'm going to close this issue, but please re-open it if there's a problem.

**Comment by adrianFour13** [comment]
Hello @eKoopmans, I tried converting an html element with a canvas that is being drawn once the page is loaded coming from a dynamic data api source. Now once i run my code to conver this element to PDF it seems it will not render show the  canvas in the pdf. Did miss something? thank you!
