### ISSUE TITLE
Rich text HTML not rendering

### ISSUE THREAD

**Issue by faisal-ashfaq-confiz** [eKoopmans/html2pdf#15]
Hi,
 
First of thanks for the great jsPDF and html2canvas wrapper. The most amazing thing is it's hassle free links within PDF.

I am having a problem with renderng rich HTML which I am fetching from  a WYSIWYG area using jQuery text editor http://jqueryte.com/ but when it's rendered inisde HTML table there is only whitespaces in place of ol, ul and li.

Can you give me direction how to cope with this?

Many thanks,
Faisal

**Comment by eKoopmans** [comment]
Hi @faisal-ashfaq-confiz, yes I see the problem. In my testing, the text in each list-item shows up, but not the bullets/numbers before each item - is that right?

It looks like it is a problem in `html2canvas`, which this tool relies on for converting the HTML into an image. [Here's the relevant issue](https://github.com/niklasvh/html2canvas/issues/177) on their issue-tracker. Unfortunately there's not much I can do until it's resolved on their end, sorry!

**Comment by eKoopmans** [comment]
Closing - this is an issue in html2canvas, can't be solved on this end.
