### ISSUE TITLE
create pdf with all elements of a certain class

### ISSUE THREAD

**Issue by vzR** [eKoopmans/html2pdf#16]
If I have an accordion or tab element, would it be possible to create a pdf with certain elements of a class particular class?
for example this fiddle: https://jsfiddle.net/o0kL8zkk/12/  has the first two tabs with a class of "print-this". Is there a way to only make a pdf only of those particular tabs?
Also, there are some problems that I need to understand better:
1. html2pdf only makes pdfs of images
2. (deriving from 1) everything made pdf needs to be seen, you can't have a pdf of an element with a class of "hidden" in css?

**Comment by eKoopmans** [comment]
Hi @vzR, good questions! Right now, html2pdf uses [html2canvas](https://github.com/niklasvh/html2canvas) to turn the HTML into an image, and then slices those images up onto separate PDF pages. So a lot of those details about what gets rendered and how depends on html2canvas.

So to answer your questions:

- the way html2canvas works, it won't render anything with `display: none` or `visibility: hidden`, but you **can** create an element with `opacity: 0` and render its descendants normally (this is how html2pdf operates)

- there's no way in html2canvas to force a hidden element to render, but you **can** do the opposite - if you want to prevent an element from rendering, set the attribute `data-html2canvas-ignore="true"` (more details [here](https://github.com/niklasvh/html2canvas/issues/126))

- to make it render **only** the tabs you want, you could write a script to make sure those elements are visible and the others are not (by setting `data-html2canvas-ignore` or just CSS `display: none`) and run it just before calling html2pdf, then restore everything to original when it's done (by using the `onrendered` argument to html2canvas, more info [here](https://html2canvas.hertzen.com/documentation.html))

Good luck!

**Comment by eKoopmans** [comment]
Closing, hopefully I was able to resolve your issue.
