### ISSUE TITLE
how to call setDisplayMode from jsPDF when using html2pdf

### ISSUE THREAD

**Issue by delgah** [eKoopmans/html2pdf#18]
Hi eKoopmans, hope you're doing well
Is there a way to call setDisplayMode from jsPDF when using html2pdf?
Our code is basically doing this:
...
var parameters = {
	margin:			0,
	filename:		'test_jpeg.pdf',
	image:			{ type: 'jpeg', quality: 1 },
        html2canvas:	{ dpi: 192 },
        jsPDF:			{ unit: 'mm', format: [ width, height], orientation: 'portrait' }
					 };
    html2pdf(table, parameters);
...
But in addition we would like to call setDisplayMode to configure layout='single' and pmode='UseOutlines'

Many thanks in advance

**Comment by eKoopmans** [comment]
Hey @delgah, sorry to leave you waiting! I'm planning to add more functionality to allow more customization (see #12, #14), but haven't gotten around to it yet. Sorry!

**Comment by eKoopmans** [comment]
Hi, I have just pushed a new branch, [new-api](https://github.com/eKoopmans/html2pdf/tree/new-api), which is ready for testing! [The readme](https://github.com/eKoopmans/html2pdf/tree/new-api#advanced-usage) has all the information on the new API. Please let me know if there are any problems with it - I want to make sure it's stable before merging into master!

For this specific request, you could create the PDF object ahead of time, set the settings, then pass it into html2pdf:

```js
var pdf = new jsPDF();
pdf.setDisplayMode(1, 'single', 'UseOutlines');
html2pdf().from(element).set({ pdf: pdf }).toPdf().save();
```

**Comment by eKoopmans** [comment]
Hi, closing as resolved by the v0.9.0 new API.

**Comment by vimalprasad** [comment]
Hi eKoopmans,
    While i am using html2pdf  working fine but in console log "ERROR Error: Uncaught (in promise): [object Event] "  error occured . Any idea  ? My Code in .ts


    var element = document.getElementById('contentToConvert');
      var opt = {
        margin:       .2,
        filename:     'myfile.pdf',
        image:        { type: 'jpeg', quality: 1 },
        html2canvas:  { scale: 2 },
        jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
      };
      let this_ =this;
      html2pdf().set(opt).from(element).toPdf().get('pdf').thenCore(function (pdf) {
        console.log("image connnnnnn",pdf);
        this_.pdfPreviewImage = pdf.output('bloburl');
        this_.pdfPageView = true;
      }, error => {
        console.log("error occured");
      });

**Comment by CrazyOvi** [comment]
HI to all.
Could you please help me with solving a problem? I have a code that creates a PDF using html2pdf and it works grate, except when I run it from iPhone. If I have more pages (like over 7) it renders the PDF with pages that contain only the header and footer.


      // optiunile definite pentru salvarea documentului
      var opt = {
        margin: [20, 10, 10, 5], // top, left, bottom, right
        filename: fileName,
        image: {
          type: "jpeg",
          quality: 1.0,
        },
        html2canvas: {
          scale: 1,
          windowWidth: 1024,
          dpi: 192,
        },
        jsPDF: {
          unit: "mm",
          format: "a4",
          orientation: "landscape",
        },
        pagebreak: {
          // mode: ["avoid-all", "css", "legacy"],
          // before: ".pageInPDF",
          // after: ".stepInPDF",,
        },
      };

      // document saving
      var docPDF = html2pdf()
        .from(pdfBody)
        .set(opt)
        .toPdf()
        .output()
        .get("pdf")
        .then((pdf) => {
          var totalPages = pdf.internal.getNumberOfPages();
          for (var i = 1; i <= totalPages; i++) {
            pdf.setPage(i);
            pdf.setFontSize(20);
            pdf.setTextColor(0);

            // facem HEADAER - LOGO
            pdf.addImage(require("../assets/logo.png"), "PNG", 20, 3.5, 20, 10);

            // facem HEADER - TEXT
            pdf.text(45, 10.5, "TASK ANALYSIS");

            // facem FOOTER
            pdf.setFontSize(10);
            pdf.text(10, 205, "PAGE " + i + "/" + totalPages);
          }
        });

      await docPDF
        .outputPdf()
        .then((pdf) => {
          this.sendPDF(btoa(pdf), fileName); // function that sends the info (base64 of PDF and filename) to backend
        })
        .save();

I saw someone went to every page and add it one at a time - but I don't know how to implement that in this one.
I understand that the problem comes from Safari canvas limitations and creating and adding one page at a time would be the solution - could anyone help me?
Thanks for your replies.
