### ISSUE TITLE
Is there a way to get PDF file? 

### ISSUE THREAD

**Issue by axiom88-guru** [eKoopmans/html2pdf#186]
Hi , 
I've seen lots of discussions about this issue: #54 , #181 
But I don't see any updates...
does anyone know how to get pdf file ?

**Comment by larsomen** [comment]
html2pdf().from(element).set(opt).toPdf().get('pdf').then(function (pdf) {
      var totalPages = pdf.internal.getNumberOfPages();
      for (i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        pdf.setFontSize(10);
        pdf.setTextColor(150);
        pdf.text('Page ' + i + ' of' + totalPages, pdf.internal.pageSize.getWidth()/2, 10,{align: "center"});
      }
    }).save();

I use this piece of code (that i found somewhere here on github) to add page numbers to the top of the pdf. You will be able to edit the PDF as a jsPDF instance in the part where I add the pagenumbers.

**Comment by eKoopmans** [comment]
Hi @axiom88-guru, it depends what you mean. Standard usage will create the PDF file and prompt the user to download it:
```js
html2pdf(element);
// or:
html2pdf().from(element).save();
```

If you mean you want to store the PDF's contents in a variable, you could use code like this:

```js
html2pdf().from(element).toPdf().output('datauristring').then(function (pdfAsString) {
    // The PDF has been converted to a Data URI string and passed to this function.
    // Use pdfAsString however you like! For instance:
    console.log(pdfAsString);
});
```

Good luck! I'm closing this issue, reopen it if it's still a problem.
