### ISSUE TITLE
line height different in pdf

### ISSUE THREAD

**Issue by sandroden** [eKoopmans/html2pdf#188]
I realized that line height of the pdf version is different from the original html, resulting in more dense text. That is a real problem to me as I intended the html as "what you see is what you get" but the result is really different. 
How can I influence the rendering? the html I'm rendering is a scaled version of a pdf in A4 format. I thought html2canvas did an exact rendering. What I'm doing now is:

```
    savePdf () {
      let opt = {
        filename: 'cv.pdf',
        enableLinks: true,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: {
          scale: 8,
          width: 310,
          letterRendering: true,
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      }
      html2pdf().set(opt).from(document.getElementById('printable-cv')).save()
    },
```
is there a way to debug what font-size is really used and which line-height is applied?

**Comment by sandroden** [comment]
A hint on how to proceed to investigate this issue would be a perfect, great gift for Christmas... I don't mind if it will arrive some days late... thank you in advance and Merry Christmas...

**Comment by sandroden** [comment]
Thanks @abumphy it worked. I really believed I already tried it but it was somehow stripped from the final version. There's still some problem as I render text that comes from an html editor, so that it contains paragrah and headers, but up to now it seems it renders quite similarly to the html, and that's my goal.

**Comment by eKoopmans** [comment]
Hi @sandroden @abumphy I'm glad you were able to solve the issue. The `line-height` etc isn't explicitly changed anywhere, but at one point in the process everything is cloned and it's possible that styles got lost there. I hope to improve that behaviour.
