### ISSUE TITLE
"html2pdf__page-break" gives unexpected vertical left aligned line

### ISSUE THREAD

**Issue by alundiak** [eKoopmans/html2pdf#2]
@eKoopmans not sure if this is an issue (yours or jsPDF) or designed feature.

My HTML 

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.debug.js"></script>
    <script src="lib/html2canvas.min.js"></script>
    <script src="lib/html2pdf.js"></script>
</head>
<body>
     <div id="element-to-print">
        <span>I'm on page 1!</span>
        <div class="html2pdf__page-break"></div>
        <span>I'm on page 2!</span>
    </div>
    <script type="text/javascript" src="./index.js"></script>
</body>
</html>
```

So having this
```
<span>I'm on page 1!</span>
<div class="html2pdf__page-break"></div>
<span>I'm on page 2!</span>
```

WITH NO custom CSS code gives me a hint I would expect just text on 2 pages.

My JS:

```js
var element = document.getElementById('element-to-print');
const options = {
    margin: 10,
    filename: pdfFileName,
    image: {
        type: 'jpeg',
        quality: 0.98
    },
    html2canvas: {
        dpi: 192,
        letterRendering: true
    },
    jsPDF: {
        orientation: 'portrait'
    }
}

html2pdf(element, options);
```

Soch code gives me PDF, and I see some vertical line in content. 
This is how Chrome PDF viewer shows:
<img width="319" alt="screen shot 2017-05-03 at 20 43 05" src="https://cloud.githubusercontent.com/assets/2131633/25676254/b37ee592-3041-11e7-897d-2cbb6795bc2a.png">

<img width="399" alt="screen shot 2017-05-03 at 20 43 11" src="https://cloud.githubusercontent.com/assets/2131633/25676256/b88aaec2-3041-11e7-808e-1a93f8c4f356.png">

And this is how Adobe Reader on MacOS shows:
<img width="425" alt="screen shot 2017-05-03 at 20 43 22" src="https://cloud.githubusercontent.com/assets/2131633/25676272/c6221bec-3041-11e7-986e-9d7cf1de2883.png">
<img width="383" alt="screen shot 2017-05-03 at 20 43 30" src="https://cloud.githubusercontent.com/assets/2131633/25676278/cb6a510a-3041-11e7-87cf-c320e24b9f3e.png">

Left aligned from the text, and among whole pages I see vertical line, presumably left-broder, etc.

@eKoopmans will u agree with me, that my expectation TO NOT have that line does at least some sense?

**Comment by eKoopmans** [comment]
Yep, that looks like a problem! I'll look into it.

**Comment by lidijarad** [comment]
Hi @eKoopmans thank you for your library, I found a similar error, and this happened if I changed the margin != 1. If margin is set to 1, then the output is ok.

**Comment by eKoopmans** [comment]
Hi @alundiak @lidijarad, I'd definitely like to resolve this issue but I haven't yet been able to reproduce it. It could be a platform thing. Could you please:

1. Create a fork of [this jsFiddle](https://jsfiddle.net/o0kL8zkk/) that illustrates the issue (the dependencies are already included in the fiddle), and
2. Tell me what browser, OS, and PDF viewer you're using?

Thanks!

**Comment by alundiak** [comment]
@eKoopmans 
This [jsFiddle example](https://jsfiddle.net/landike/8q7ce58y/) uses your repo js files via raw access. And result file.pdf is with vertical lines and black region.

`html2canvas 0.5.0-beta4`
`jspdf/1.3.4/jspdf.debug.js`

I also tried with `https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.5.0-beta4/html2canvas.min.js`which is in fact `beta-3` - result the same.

[file (1).pdf](https://github.com/eKoopmans/html2pdf/files/997751/file.1.pdf)

**Comment by eKoopmans** [comment]
Hi, as I [mentioned](https://github.com/eKoopmans/html2pdf#dependencies) in the readme, html2pdf works best with the custom builds of html2canvas and jsPDF included in the `/vendor/` directory. Specifically here, the black bars are caused by an html2canvas issue with [offscreen rendering](https://github.com/niklasvh/html2canvas/pull/1083), which is resolved in the custom build in `/vendor/`.

The jsFiddle I linked uses the `/vendor/` files for both dependencies. [Here's](https://jsfiddle.net/z93667yd/1/) a fiddle with your code in it, the result for me doesn't produce any black bars.

**Comment by alundiak** [comment]
ok, then close this issue, if it's not an issue.

**Comment by alundiak** [comment]
I think it's bug, because as end consumer, I want to use 3rd party libs and not depends on your own build of the lib code. Otherwise such lib is not well maintainable. When new version/release of html2canvas appear, u will update ur repo and I will have to update my code with file from your repo directly. I would like to install by npm or bower  module/component and rely on it strictly from official releases.

**Comment by eKoopmans** [comment]
@alundiak I hear you, I'd rather be able to use the stock versions too, but right now that offscreen rendering issue is an unavoidable bug in html2canvas. There's no way I could fix it from the outside. I'm waiting on the pull request to be merged in over there, as soon as it is then there will be no need for custom builds!

Your initial issue, with the dark vertical strip to the left of the text, seems separate from the black boxes, and I'd still like to resolve it. Have you tested with the custom html2canvas?

**Comment by alundiak** [comment]
> html2canvas issue with offscreen rendering, which is resolved in the custom build in /vendor/

If u did changes in minified file, then I would suggest u add comment on header of file, so that code researcher realize, that minified file IS NOT the same version as version published on CDN or elsewhere. Doing this, u will show, the reason why u have copy of file in code itself. U know - if I saw it in code, I would know why u have copy. Yes I read it in readme, and I realise the reason of copy in vendor.  But hope u agree, that from code perspective, it's not informative, that 3rd-party library has been somehow changed.

**Comment by eKoopmans** [comment]
You're right @alundiak, I've added info about the custom builds to both vendor dependencies in 474b36e2e7b77194a126609af90e6dda6b7258d9.

**Comment by alundiak** [comment]
@eKoopmans this is ["html2pdf usage - NEW" jsfiddle](https://jsfiddle.net/landike/w75ahym5/).
It uses: 
- https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.debug.js
- https://raw.githubusercontent.com/eKoopmans/html2pdf/master/vendor/html2canvas.min.js (with ur: "2017-05-13 Custom build by Erik Koopmans, featuring latest bugfixes and features")
- also tried with this https://rawgit.com/eKoopmans/html2pdf/master/vendor/html2canvas.min.js
- https://rawgit.com/eKoopmans/html2pdf/master/src/html2pdf.js

Results is the same:
[file_May-13-2017_.pdf](https://github.com/eKoopmans/html2pdf/files/998947/file_May-13-2017_.pdf)

**Comment by eKoopmans** [comment]
You're going to say this isn't obvious - and you'd probably be right - but again as mentioned in the [readme](https://github.com/eKoopmans/html2pdf#install), the order of the dependencies is important.

jsPDF includes an out-of-date version of html2canvas internally, so you need to include html2canvas *after* jsPDF and *before* html2pdf. I've updated the order of the includes in [your fiddle](https://jsfiddle.net/w75ahym5/3/) (the only change I made is including html2canvas before html2pdf instead of after).

Maybe it would be best to package all of the dependencies together with Browserify and offer a html2pdf.bundle.js to avoid all of these sorts of issues. In any case, please try the link I sent and let me know if it's still producing the black bars or boxes (neither show up for me).

**Comment by alundiak** [comment]
@eKoopmans  :) I tried, and the reality of JS proves that all works fine now. Silly, but have to admit. One bundle would be great.

**Comment by eKoopmans** [comment]
Agreed, I'll make a bundle (and NPM package info etc) in the near future. Thanks for helping track down this problem!

**Comment by lidijarad** [comment]
@eKoopmans, I have updated the order in which I load the files and am using your modified versions of the other libs and the output of the pdf seems to be good now. Thank you so much for tending to this so promprly.

**Comment by eKoopmans** [comment]
No problem @lidijarad! I'm glad everything's working well, let me know if you run into any other problems.

**Comment by eKoopmans** [comment]
Btw, bundle was added in v0.8.0.
