### ISSUE TITLE
How include image into PDF file?

### ISSUE THREAD

**Issue by zheleznyak** [eKoopmans/html2pdf#20]
Hi there. 
At first, thank you for your script, I think this is great.
Second, I need to know is there oportunity to include image into PDF file. I've tried, but there is only white empty space instead of image.

When I'm trying to put `<div>` with image background, I've this error:
`Uncaught (in promise) DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at Function.html2pdf.makePDF (file:///C:/Users/%D0%94%D0%B5%D0%BD%D0%B8%D1%81/Desktop/test%20JS%20send%20mail/html2pdf/html2pdf.js:197:32)
    at Object.opt.html2canvas.onrendered (file:///C:/Users/%D0%94%D0%B5%D0%BD%D0%B8%D1%81/Desktop/test%20JS%20send%20mail/html2pdf/html2pdf.js:80:16)
    at file:///C:/Users/%D0%94%D0%B5%D0%BD%D0%B8%D1%81/Desktop/test%20JS%20send%20mail/html2pdf/html2canvas.min.js:8:11854`

Thank you in advance.

**Comment by zheleznyak** [comment]
Isssue was solved once I transfer it rom localhost to my server. Thanks

**Comment by eKoopmans** [comment]
Hi @zheleznyak, glad you solved the issue! The other issue you may run into is with 'cross-domain images', if you're trying to load images that aren't on your own server. There's more info on that [here](https://github.com/niklasvh/html2canvas/issues/1130#issuecomment-302763643).
