### ISSUE TITLE
Page Numbers

### ISSUE THREAD

**Issue by enriquezrene** [eKoopmans/html2pdf#21]
I need to add the page number in a format like:

Page 1 / 3
Page 2 / 3
Page 3 / 3

is there a way to do this?

**Comment by eKoopmans** [comment]
Hi @enriquezrene, yes, here's what I would suggest. You can use the new branch I've mentioned over [here](https://github.com/eKoopmans/html2pdf/issues/14#issuecomment-318798955) and use the `pdfCallback` option to get the final jsPDF object before outputting. Then you could loop through each page and add your page # text on - see the [jsPDF documentation](https://github.com/MrRio/jsPDF) for more info on how to use the jsPDF object.

Note that the branch with `pdfCallback` is just a temporary solution, I'm planning an update soon that will add more flexible options for using html2pdf, but it should work for now.

**Comment by murcoder** [comment]
Because it cost me some time:
If someone is looking the **number of pages**, you can do that (using [this branch](https://github.com/eKoopmans/html2pdf/tree/pdf-callback)):

```
function myCallback(pdf) {
 //get the number of pages
 var totalPages = pdf.internal.getNumberOfPages();
 console.log(totalPages);

  //Optional: Save PDF
  pdf.save('checkliste.pdf');
}

html2pdf(element, {
  pdfCallback: myCallback,
  // Any other options you want to set...
});
```

**Comment by eKoopmans** [comment]
Hey @murcoder, thanks for the contribution! Do you have a source on how `pdf.putTotalPages().internal.getNumberOfPages()` works? The `jsPDF` documentation is a bit outdated.

**Comment by murcoder** [comment]
Hi @eKoopmans! Because I couldn't find a good documentation, it was pretty hard to find how to get the page numbers. But in the end I found [this helpful thread](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/199) and I checked out the source code.

**Comment by eKoopmans** [comment]
Hi, I have just pushed a new branch, [new-api](https://github.com/eKoopmans/html2pdf/tree/new-api), which is ready for testing! [The readme](https://github.com/eKoopmans/html2pdf/tree/new-api#advanced-usage) has all the information on the new API. Please let me know if there are any problems with it - I want to make sure it's stable before merging into master!

For this specific request, you could make changes to the PDF object before saving like so:

```js
html2pdf().from(element).toPdf().get('pdf').then(function (pdf) {
  // Your code to alter the pdf object.
}).save();
```

**Comment by knox2** [comment]
Tried adding page numbers but displays nothing

```
html2pdf().from(element).set(opt).toPdf().get('pdf').then(function (pdf) {
  var totalPages = pdf.internal.getNumberOfPages();

  for (i = 1; i <= totalPages; i++) {
    pdf.setPage(i);pdf.setFontSize(10);
    pdf.setTextColor(150);
    pdf.text(pdf.internal.pageSize.width - 100, pdf.internal.pageSize.height - 30, 'Page '+i+' of '+totalPages);
  } 
}).save();
```

**Comment by kl3sk** [comment]
First the `pdf.text` arguments are not in the right order
Then you should call `getHeight()` and `getWidth()` on `pdf.internal` Object

```js
html2pdf().from(element).set(opt).toPdf().get('pdf').then(function (pdf) {
  var totalPages = pdf.internal.getNumberOfPages();

  for (i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(10);
    pdf.setTextColor(150);
    pdf.text('Page ' + i + ' of ' + totalPages, pdf.internal.pageSize.getWidth() - 100, pdf.internal.pageSize.getHeight() - 30);
  } 
}).save();
```

**Comment by eKoopmans** [comment]
Thanks @kl3sk! That looks like an effective way of adding page numbers.

Closing as resolved by [this post](https://github.com/eKoopmans/html2pdf/issues/21#issuecomment-447028134). Thanks again!

**Comment by kl3sk** [comment]
@eKoopmans  welcome 😃

**Comment by AthalG** [comment]
@eKoopmans @kl3sk Thank you for this!
However, it doesn't appear on the document (although when I search for it's there but not in the page itself) I tried to play around with the x and y of the text but doesn't to work either. Is there something that I can do to fix it?

**Comment by eKoopmans** [comment]
Good point, the coordinates sent to `pdf.text()` will be in your document's units - so if you're using inches for instance (vs the default mm), the values will differ.

**Comment by jloguercio** [comment]
Its possible to add HTML to Header and Footer?

**Comment by Jithesh-Menon** [comment]
> First the `pdf.text` arguments are not in the right order
> Then you should call `getHeight()` and `getWidth()` on `pdf.internal` Object
> 
> ```js
> html2pdf().from(element).set(opt).toPdf().get('pdf').then(function (pdf) {
>   var totalPages = pdf.internal.getNumberOfPages();
> 
>   for (i = 1; i <= totalPages; i++) {
>     pdf.setPage(i);
>     pdf.setFontSize(10);
>     pdf.setTextColor(150);
>     pdf.text('Page ' + i + ' of ' + totalPages, pdf.internal.pageSize.getWidth() - 100, pdf.internal.pageSize.getHeight() - 30);
>   } 
> }).save();
> ```

I tried the same approach. It didn't work for me. Also as @jloguercio  asked, is there a possibility to add HTML to header and footer.

**Comment by iamtekson** [comment]
For header you can simply try

```javascript
pdfObject.text("my header text", 10, 10)
```
This will set the header at position x=10, y=10 at every page. Also for footer you can do in same way.

**Comment by mayanksdudakiya** [comment]
@kl3sk Thanks for the solution. Your solution worked after defining the variable `i` in for loop as follow.

```
html2pdf()
                    .from(pdfHTML)
                    .set({
                        margin:       [30, 0, 30, 0],
                        filename:     'file.pdf',
                        image:        { type: 'jpeg',quality: 0.98 },
                        html2canvas:  { dpi: 96, scale: 1, scrollX: 0, scrollY: 0, backgroundColor: '#FFF' },
                        jsPDF:        { unit: 'pt', format: 'a4', orientation: 'p' },
                        pagebreak: { before: '.page-break', avoid: 'img' }
                    })
                    .toPdf()
                    .get('pdf').then(function (pdf) {
                      var totalPages = pdf.internal.getNumberOfPages();
                      
                      for (let i = 1; i <= totalPages; i++) {
                        pdf.setPage(i);
                        pdf.setFontSize(10);
                        pdf.setTextColor(150);
                        pdf.text('Page ' + i + ' of ' + totalPages, pdf.internal.pageSize.getWidth() - 100, pdf.internal.pageSize.getHeight() - 10);
                      } 
                    }).save();
```

**Comment by Yavar-localmedia** [comment]
> Its possible to add HTML to Header and Footer?

**Comment by Yavar-localmedia** [comment]
Thanks for your job, it works perfect , i just wanted to ask you, It's possible to add HTML to Header and Footer?

**Comment by trinath-katari** [comment]
![image](https://user-images.githubusercontent.com/93243024/154221328-b08729c9-2faf-4e17-a7b2-9d44f9618841.png)

i am using the same code in  typescript(angular) it is not working

**Comment by Krookroo231** [comment]
@trinath-katari  I am having the same issue, have you resolved it already ?

**Comment by skgacharya** [comment]
I'm using the same code in ASP.Net with MVC Jquery it is not working for me.
![image](https://github.com/user-attachments/assets/419e24d8-860a-4c55-8aa4-c24c2ead1d10)

**Comment by raza2022** [comment]
@skgacharya or for anyone facing the same issue, I found that these calculations differ based on the page orientation/units, etc so if you can't find the header/footer try to change position by increasing/decreasing the values when it printed somewhere then adjust based on your specific design needs for example these values working for my design
```
const totalPages = pdf.internal.getNumberOfPages();
            for (var i = 1; i <= totalPages; i++) {
                pdf.setPage(i);
                pdf.setFontSize(12);
                pdf.setTextColor('#308462');
                pdf.text(pdf.internal.pageSize.getWidth() - 80, 15, `REPORTE ENCUESTA ${moment(new Date)?.format('DD/MM/YYYY')}`);
                pdf.text('Pag.' + i + ' de ' + totalPages+'', pdf.internal.pageSize.getWidth() - 40, pdf.internal.pageSize.getHeight() - 8);
            }
            }).save()
```
