### ISSUE TITLE
In IE 10 & above browser, PDF file downloading issue

### ISSUE THREAD

**Issue by bangararaju** [eKoopmans/html2pdf#24]
In IE 10 & above the PDF file is downloads, but (Ex:- Out of 14 pages data only 11 pages are downloaded and in that 5 pages  data are visible and remaining pages visible black screen )

**Comment by bangararaju** [comment]
Hi,  I am giving **more information** about the above issue- 
Using script files :- jquery-1.12.3.min.js, jspdf/1.3.4/jspdf.min.js, html2canvas/0.4.1/html2canvas.min.js
Code  calling in button click- 
var pdf = new jsPDF("p","pt","letter");
 pdf.internal.scaleFactor = 2.00;
 var options = {pagesplit: true};
 pdf.addHTML(document.body,options,function() { // here reading the entire body content
        pdf.save("HTMLTOPDFFILE.pdf"); //This will output the PDF in a new window
 });	

By using this code, it's well in chrome & Mozilla browsers where as in IE browser 10 & above its behave differently, show limited pages are downloading & unable to view all data after certain limit (ex; 5 pages) remaining with black screen. 
For your reference, adding sample screen
![ie pdf issue](https://user-images.githubusercontent.com/30728464/29109294-2e4dab18-7d00-11e7-9d33-096717558394.JPG)

**Comment by bangararaju** [comment]
Thanks, have a great day. Any help is appreciated to resolve the above issue.

**Comment by eKoopmans** [comment]
Hi, the black bar issue is definitely a result of not using the version of html2canvas in the `vendor/` folder. More info [here](https://github.com/eKoopmans/html2pdf/issues/2#issuecomment-301170753).

**Comment by bangararaju** [comment]
Hi ekoopmans, while using this link **https://jsfiddle.net/o0kL8zkk**/  and add my script, css then in IE the below error throws
![capture](https://user-images.githubusercontent.com/30728464/29204141-ef52209e-7e92-11e7-8224-f43a165b5110.JPG)

Please check it. iam waiting for your response.

**Comment by eKoopmans** [comment]
You've got two open issues, I've responded to your issue regarding promises already [here](https://github.com/eKoopmans/html2pdf/issues/25#issuecomment-321545397). You need to include a Promise polyfill.

**Comment by bangararaju** [comment]
Good morning, the above issue is resolved but the data is not splitting what the user accepts. below the sample screen shot- 
![image](https://user-images.githubusercontent.com/30728464/29361665-42dfe932-82a6-11e7-8147-535abf886f8e.png)
Note:- same issue for image also.
Any help is appreciated.

**Comment by eKoopmans** [comment]
Take a look at [this issue](https://github.com/eKoopmans/html2pdf/issues/13#issuecomment-305950719) for more info on that problem. You can use

**Comment by bangararaju** [comment]
Hi, I used page breaks for page splitting. but the data in page is getting dynamically. so, we don't know how much data is getting while generating PDF. The Text or images breaks in middle.
