### ISSUE TITLE
Issue in downloading PDF

### ISSUE THREAD

**Issue by bangararaju** [eKoopmans/html2pdf#25]
While using the latest jspdf & html2pdf js files, downloading the pdf from any browser(here i used chrome). In my HTML i have 15 pages (while downloading data visible all blank pages). I Tested with different trials then upto 7 pages html we can view download as pdf. Above 7 pages we are getting blank pages.Can anyone resolve this. please update.

**Comment by eKoopmans** [comment]
Hi @bangararaju, are you using the version of html2canvas available in the [vendor folder](https://github.com/eKoopmans/html2pdf/tree/master/vendor) of this package? It has some additional bugfixes, including one that I think resolves your issue. See [the readme](https://github.com/eKoopmans/html2pdf/blob/master/README.md#install) for a bit more info.

**Comment by bangararaju** [comment]
Hi @eKoopmans, using the above vendor folder docs and below the reference using for html2pdf.js
( https://rawgit.com/eKoopmans/html2pdf/master/src/html2pdf.js).After using this files in chrome its working. where as in IE browser (IE10 & above) get the error- promise issue (it's in CDN only) .Can anyone get this type of issue.

**Comment by eKoopmans** [comment]
Hi, yes html2canvas relies on Promises, which are supported natively in modern browsers, but older browsers (like IE) require a polyfill. See the [html2canvas readme](https://github.com/niklasvh/html2canvas/blob/master/readme.md#usage) for more info.

**Comment by iammikek** [comment]
@eKoopmans  the link above to the ' html2canvas readme' is a dead link, can you post another?

**Comment by eKoopmans** [comment]
Oops, I totally missed your comment @iammikek! Very sorry. I've fixed the link in my original comment.
