### ISSUE TITLE
Data split issue in PDF

### ISSUE THREAD

**Issue by bangararaju** [eKoopmans/html2pdf#26]
Hi, I used page breaks for page splitting. but the data in pages is getting dynamically. so, we don't know how much data is getting while generating PDF. The Text or images breaks in middle.

**Comment by bangararaju** [comment]
Hi good morning, providing more information about the above issue -
![image](https://user-images.githubusercontent.com/30728464/29821560-ff952fda-8ce5-11e7-9730-b8f27b2c6636.png)- for your reference added image -data /Image is splitting. 

Can any one give advice to resolve this. Waiting for your reply. Have a nice day..!

**Comment by eKoopmans** [comment]
Hey @bangararaju, yes, this is something I hope to make a solution for in the future, but I don't have a fix right now. You can see [this comment](https://github.com/eKoopmans/html2pdf/issues/13#issuecomment-307312497) for one user's solution.

**Comment by eKoopmans** [comment]
Hi, closing as resolved by the v0.9.1 page-break features.

**Comment by bangararaju** [comment]
> Hi, closing as resolved by the v0.9.1 page-break features.

thank you
