### ISSUE TITLE
Incorrect pxPageHeight calculation

### ISSUE THREAD

**Issue by Colinh84** [eKoopmans/html2pdf#3]
The pxPageHeight variable used to determine the pixel height of blank space to insert on a page break, is calculated wrong if you initialize the jsPDF options object with { unit: 'px' }. The calculation currently used is:

```javascript
var pxPageHeight = pageSize.inner.height * pageSize.k / 72 * 96;
```

This calculation works fine if jsPDF options is set with inches as the unit value, but starting with pixels turns this into a complete mess. I haven't tried with other unit types yet, but expect similar results.

To breakdown your calculation as I understand it, **pagesize.inner.height** is the page height value returned from jsPDF, in the units specified in the options init. **pageSize.k** is also send from jsPDF and is the conversion ratio to convert inner.height to pt units. **72** is the number of pt units in an inch, and **96** is the number of pixels in an inch.

So, if I initialize jsPDF in px units, with landscape mode and a paper size with a height of 816px (corresponds to 8.5 inches with standard conversion factor of 96px per inch) pxPageHeight ends up calculating as:

816 * 1.33333333333333 / 72 * 96 = 1450.66 px

As the page is initialized with 816 px height, now html2pdf incorrectly thinks the page height is 1450px, and makes a mess of the page breaks!

To get around this, I initialized jsPDF unit option with 'in', as the calculation works fine converting inches to pixels, but not pixels to pixels; Since 'px' is a valid unit option for jsPDF, I think it should be accommodated in the calculation, and also tested for validity against all other unit types.

**Comment by Colinh84** [comment]
If the calculation is slightly modified to:

```javascript
var pxPageHeight = pageSize.inner.height / pageSize.k / 72 * 96;
```

The correct px pageHeight comes out the end when starting with pixels:

816 / 1.33333333333333 / 72 * 96 = 816 px

So, the conversion factor of 1.333333333333333 supplied by pageSize.k is the wrong one to be using with multiplication, and should actually be **0.75**

**Comment by eKoopmans** [comment]
@Colinh84 you beat me to it! Take a look at MrRio/jsPDF#1173 - I borrowed jsPDF's conversions, and the pixel conversion was backwards. I'll fix that ASAP, good catch.

**Comment by eKoopmans** [comment]
Fixed and updated, let me know if the issue's resolved.

**Comment by Colinh84** [comment]
@eKoopmans Just gave it a try and works as expected now. Thanks!
