### ISSUE TITLE
Empty page when using html2pdf__page-break

### ISSUE THREAD

**Issue by chrishaensel** [eKoopmans/html2pdf#30]
Good morning

I have the following layout of a HTML element that I am putting into a PDF using html2pdf

```
<outer-div>
	<inner-div>Some content</inner-div>
	<inner-div>Some content</inner-div>
	<inner-div>Some content</inner-div>
	<inner-div>Some content</inner-div>
	<inner-div>Some content</inner-div>
	<inner-div>Some content</inner-div>
	<inner-div>Some content</inner-div>
	<inner-div>Some content</inner-div>
	.....
</outer-div>
```

After a specified number of inner-divs (like 25), I append a div with the class `html2pdf__page-break` to add a page break - and then continue to append the remaining inner-divs to be continued on the second page.

The problem is that the first page is now empty and just the remaining content shows up on the second page.

Am I missing something here?

**Comment by chrishaensel** [comment]
Nevermind... I found my problem. I was using [mustachejs](https://github.com/janl/mustache.js/) to append the inner divs to the outer div. The problem was that this happens async - so I needed to append the page break within the callback function of the mustachejs-function... 

Sorry for thinking it had to do with your library :)

**Comment by eKoopmans** [comment]
No worries @chrishaensel, glad you got it sorted!
