### ISSUE TITLE
Page break does not seem to increase document height 

### ISSUE THREAD

**Issue by scriptmonkey69** [eKoopmans/html2pdf#31]
When I use the page break functionality, they are placed exactly where I want them, but the document gets cropped at the bottom by the amount of space added by the page breaks.

Unfortunately this is resulting in an approval element being omitted from the pdf.

[form_nopagebreaks.pdf](https://github.com/eKoopmans/html2pdf/files/1287340/form_nopagebreaks.pdf)
[form_pagebreaks.pdf](https://github.com/eKoopmans/html2pdf/files/1287341/form_pagebreaks.pdf)

Below is the code we use to save the html element as a PDF

`viewModel.SaveHtml2Pdf = function() {
    var element = $('div.data-entry-form:first');
    var source = element[0];

    var username = $('a.user-name:first').text().replace(/\s+/g, '').replace(/"/g, '');
    var friendlyForm = friendlyFormName(viewModel.FormType());
    var formid = viewModel.FormData.Id();

    html2pdf(source,{
        margin: 20,
        filename: 'complianceform.pdf',
        image: { type: 'jpeg', quality: 1 },
        html2canvas: { dpi: 300, letterRendering: true },
        jsPDF: { unit: 'mm', format: 'A4', orientation: 'portrait' },
        jsPDFProperties: {
            title: 'CAFE Compliance Form',
            subject: friendlyForm + ' - ' + formid,
            author: username,
            keywords: 'CAFE, cafe, compliance, ' + friendlyForm,
            creator: 'CAFE'
        },
        title: 'CAFE - ' + friendlyForm + ' - ' + username
    });
};`

**Comment by scriptmonkey69** [comment]
Think this issue is not related to the html2pdf code but related to the html2canvas cropping the image.

**Comment by eKoopmans** [comment]
Hi @scriptmonkey69, sorry again for the delay. This looks like the [offscreen rendering bug](https://github.com/niklasvh/html2canvas/pull/1083). Try the version of html2canvas in the `/vendor/` directory of this package, it might resolve your problem. More info [here](https://github.com/eKoopmans/html2pdf/issues/2#issuecomment-301170753).

**Comment by scriptmonkey69** [comment]
Worked like a charm thank you. Will be deploying fix to production this
week.

Keep up the good work.

**Comment by eKoopmans** [comment]
Great, happy to help! Is it safe to close the issue?

**Comment by scriptmonkey69** [comment]
Yep

**Comment by jCabigting** [comment]
Hi @eKoopmans, I'm having this issue but for some reason I can't find the /vendor/ folder that you're pointing to. Has it been removed? And is there a permanent fix for this issue?

**Comment by eKoopmans** [comment]
Hi @jCabigting, sorry for the *long* delay.

There's no longer a /vendor/ directory, instead my suggestion would be to make sure you're using the "bundled" version of the package, `html2pdf.bundle.js`. That has the latest version of html2canvas and jsPDF bundled in. The issue described above had to do with an older version of html2canvas that should be resolved now.
