### ISSUE TITLE
Text area crops content

### ISSUE THREAD

**Issue by scriptmonkey69** [eKoopmans/html2pdf#32]
When text areas are rendered in the PDF, if the content large then the text is cropped, resulting in half a line of text. 
[cropped_textarea.pdf](https://github.com/eKoopmans/html2pdf/files/1287343/cropped_textarea.pdf)

Below is the code we use to save the html element as a PDF

`viewModel.SaveHtml2Pdf = function() {
    var element = $('div.data-entry-form:first');
    var source = element[0];

    var username = $('a.user-name:first').text().replace(/\s+/g, '').replace(/"/g, '');
    var friendlyForm = friendlyFormName(viewModel.FormType());
    var formid = viewModel.FormData.Id();

    html2pdf(source,{
        margin: 20,
        filename: 'complianceform.pdf',
        image: { type: 'jpeg', quality: 1 },
        html2canvas: { dpi: 300, letterRendering: true },
        jsPDF: { unit: 'mm', format: 'A4', orientation: 'portrait' },
        jsPDFProperties: {
            title: 'CAFE Compliance Form',
            subject: friendlyForm + ' - ' + formid,
            author: username,
            keywords: 'CAFE, cafe, compliance, ' + friendlyForm,
            creator: 'CAFE'
        },
        title: 'CAFE - ' + friendlyForm + ' - ' + username
    });
};`

**Comment by scriptmonkey69** [comment]
Fixed this issue myself by changing all the textarea objects to div.

**Comment by eKoopmans** [comment]
Hey @scriptmonkey69, I'm glad you found a solution, sorry I didn't get back to you sooner. This looks like one of many issues in the html2canvas library (which the developer there is actively improving right now).
