### ISSUE TITLE
RequireJS support

### ISSUE THREAD

**Issue by eaccka** [eKoopmans/html2pdf#34]
Has anybody gotten this library to work with RequireJS?

**Comment by eKoopmans** [comment]
Hi @eaccka, I've taken a quick look at RequireJS, but haven't used it. What problems are you running into? html2pdf has two dependencies, jsPDF and html2canvas, which should be loaded first in that order.

**Comment by drbeat** [comment]
I have also an issue with requirejs.

https://gist.github.com/drbeat/c8761828902afe73ceae257940793937

my setup looks somehow like this but requirejs always bugs about html2canvas


```
Uncaught ReferenceError: html2canvas is not defined
    at html2pdf.js:387
```

and

`Uncaught TypeError: html2pdf is not a function`

the 2nd error may be my problem as I am new to requirejs but I am quite sure that my includes and dependencies are correct
still I dont know why it spits out this error

**Comment by eKoopmans** [comment]
Hi @drbeat, you're in luck! I've got a new build that will be merged in soon (next few days) that should be much friendlier for all requires/includes. It should resolve your RequireJS issues, if not let me know - stay tuned!

**Comment by drbeat** [comment]
@eKoopmans thanks but now I rewrote your code to make it work with requirejs
if you are interested I can upload it so you can have a look

**Comment by eKoopmans** [comment]
Great, glad you solved the problem! Yes if you could share what changed to solve things that would be helpful.

**Comment by drbeat** [comment]
@eKoopmans 
https://gist.github.com/drbeat/5a823ec1d85fc3a0c2349267538457e7

as you see I restructured a bit (just for my OCD) and added AMD support

now I can call html2pdf with

```
require(['html2pdf'], function(html2pdf){
html2pdf(element);
})
```

without caring about dependencies anymore

**Comment by eKoopmans** [comment]
Hey @drbeat, thanks for the gist! Yep the original package didn't have any AMD support - when I skimmed RequireJS earlier I completely missed that requirement.

In any case, the new v0.8.0 should solve that problem. The default `dist/html2pdf.js` is packaged as UMD, which has AMD support. Closing this issue, let me know if there's any remaining issues!

**Comment by drbeat** [comment]
@eKoopmans 
tried out v.0.8.0
it is much more reliable now. thanks!

**Comment by eKoopmans** [comment]
Good to hear, @drbeat!
