### ISSUE TITLE
Not showing div content

### ISSUE THREAD

**Issue by patrabas** [eKoopmans/html2pdf#36]
Hello @eKoopmans,

I'm trying to generate a pdf from a div containing a form + tables.  When I generate it, the tables are OK but it's not showing the info inside the inputs of the form (and they have disabled text content). What is wrong with that text? Am I missing something? The div I'm sending has all the info.
![issue](https://user-images.githubusercontent.com/29792961/30650440-2a9db8fc-9e23-11e7-8440-ca9fc80dd8d7.png)

Thanks in advance!

**Comment by eKoopmans** [comment]
Hi @patrabas, this is probably the [offscreen rendering bug](https://github.com/niklasvh/html2canvas/pull/1083) in html2canvas. Try the version of html2canvas in the /vendor/ directory of this package, it might resolve your problem. More info here.

**Comment by eKoopmans** [comment]
Closing, hopefully I was able to resolve the issue.
