### ISSUE TITLE
Embedding html2canvas proxy into html2pdf

### ISSUE THREAD

**Issue by fabiomor** [eKoopmans/html2pdf#38]
Hi,

thanks for your awesome library. What i'd like to achieve is to embed proxy html2canvas rpoperties for allowing static google maps to be included into the pdf. So far i tried to do something like this, but this way the rendering includes just the static html (such as table borders, not including php db query responses, static images and google map).

Thanks

`	
	
	<script type="text/javascript">	
               html2pdf(document.getElementById('mainpage'),{
			html2canvas: {
				logging: true,
				proxy: "EXTRA/html2pdfJS/html2canvasproxy.php",
				onrendered: function(canvas) {
                    var img = new Image();
                        img.onload = function () {
                            img.onload = null;
                            document.getElementById("mainpage").appendChild(img);
                        };
                        img.src = canvas.toDataURL("image/png");
                }
			}
		});
	</script>`

**Comment by eKoopmans** [comment]
Hey @fabiomor! Really sorry about the long wait. Anything you pass in the `html2canvas` options will be sent along, including the proxy setting. That said, I don't have too much experience with html2canvas proxies. Have you tested html2canvas on its own with the same proxy settings? Do you have an example with html2canvas working and html2pdf not working?

**Comment by eKoopmans** [comment]
Closing, let me know if you're still having issues!
