### ISSUE TITLE
Huge file sizes when using png image type

### ISSUE THREAD

**Issue by Colinh84** [eKoopmans/html2pdf#4]
When initializing html2pdf with 'png' as the image type option, file sizes are approx. 32 times larger than using 'jpeg' at 100% quality. Adjusting the 'quality' option doesn't have any effect on the filesize when using type 'png', it remains constant at all levels.

**Comment by eKoopmans** [comment]
Hi @Colinh84, yes .png is a lossless image compression so it gives larger file sizes. The image type and quality options are used in the [`canvas.toDataUrl()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) conversion, and you'll see in that link that 'quality' is only used for jpeg/webp, not png. I'll try to make the documentation more clear about that limitation.

In terms of resolving the issue, my suggestion is to try using [this shim](https://github.com/ShyykoSerhiy/canvas-png-compression) which adds png compression to `canvas.toDataUrl()`. It looks like a convenient in-place solution - it should cause the `quality` setting to reduce the size of the pngs/files created. I'll add that info into the readme as well. Let me know if you try it!

**Comment by eKoopmans** [comment]
Closing this issue, hopefully your questions about pngs were resolved.
