### ISSUE TITLE
can i get npm package of this?

### ISSUE THREAD

**Issue by keshav1007** [eKoopmans/html2pdf#40]
Hi,

Since jspdf and html2canvas are available as npm packages. Do we have npm package for this as well?

**Comment by eKoopmans** [comment]
Hey @keshav1007, sure thing, I'm working on it!

**Comment by mr-solver** [comment]
hey @eKoopmans I hope it is done as npm package, wanna use in my project.

**Comment by keshav1007** [comment]
Hi @eKoopmans  is this ready?

**Comment by MickaelBZH** [comment]
An NPM package would be awesome.

**Comment by azebac** [comment]
Guys if you are using angular2> you can use it by this way:
1.- Place all the .js in a folder in assets
2.- In the index.html:
```
<script src="assets/html2pdf/jspdf.min.js"></script>
<script src="assets/html2pdf/html2canvas.min.js"></script>
<script src="assets/html2pdf/html2pdf.js"></script>
```
3.- In your component at the imports section:
`declare var html2pdf: any;`

4.- And finally in your needed function:
```
   var element = document.getElementById('card-a4');
    new html2pdf(element, {
        margin:       0,
        filename:     'myfile.pdf',
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { dpi: 192, letterRendering: true },
        jsPDF:        { unit: 'mm', format: 'a4', orientation: 'p' }
    });
```

**Comment by keshav1007** [comment]
@azebac thanks for this.. it is working properly but since i have some graphs/charts in my page those are not rendered properly.. do you have any solution for that?

**Comment by eKoopmans** [comment]
Okay, stay tuned folks! I'll be dropping a new build in the next few days, rebuilt for NPM and all your require/include needs. Just need to work out the kinks.

**Comment by eKoopmans** [comment]
Okay everyone, the NPM package is done and delivered with the new v0.8.0! You can use it with `npm install html2pdf.js` (note the `.js` in the name, there was already an NPM package named `html2pdf`). Enjoy, and let me know if there's any issues!

P.S. As [html2canvas points out](https://www.npmjs.com/package/html2canvas#how-does-it-work), even though you can now use NPM/Node to build with this package, it will never work browserless in Node. **Any package using html2pdf will need to run in the browser to work properly.** You've been warned!
