### ISSUE TITLE
Pdf export of a page with chartistjs chart

### ISSUE THREAD

**Issue by samuelgeojit** [eKoopmans/html2pdf#42]
Thankyou for the great library.
I want to export a page with chart created with [chartist.js](https://github.com/gionkunz/chartist-js).
But when exporting it to pdf  only the labels in PDF but there is no chart.
Here am adding a [JS Fiddle ](https://jsfiddle.net/o0kL8zkk/20/) that will reproduce the issue
I request you to have a look and help me to solve the same.

**Comment by albancho** [comment]
As far as I know, you can't print an SVG in a pdf directly using html2pdf. You first have to draw SVGs into a canvas (which will replace your svg), and then run the export. You may use "canvg" for this...

**Comment by eKoopmans** [comment]
Hi @samuelgeojit, yes @albancho is right! Unfortunately html2pdf is limited based on the abilities of html2canvas, which is what actually converts the HTML into an image.

As @albancho suggested, you could run [canvg](https://github.com/canvg/canvg) first on all your charts to convert them to images, then run html2pdf.

**Comment by eKoopmans** [comment]
Closing - this is an issue in html2canvas, can't be solved on this end.
