### ISSUE TITLE
Multiple Browser Issues with html2pdf

### ISSUE THREAD

**Issue by CameronBlandy** [eKoopmans/html2pdf#45]
Hi Erik,
Love using your tool but I am running into some issues when using the tool on different browsers. If I reference to your version of jspdf in the Vendor folder I get the following error:
Chrome:
html2pdf.js:393 Uncaught ReferenceError: jsPDF is not defined
    at html2pdf.js:393
Firefox:
ReferenceError: jsPDF is not defined[Learn More]  html2pdf.js:393:1
	<anonymous> https://cosmos.surrey.ca/external/tools/SiteSelector/report/html2pdf.js:393:1
IE11:
SCRIPT5009: 'html2canvas' is undefined
File: html2pdf.js, Line: 35, Column: 1

When I reference js2pdf from the the actual build: https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.debug.js 
it works fine in Chrome and Firefox but in IE I get the following error.
SCRIPT5009: 'html2canvas' is undefined
File: html2pdf.js, Line: 35, Column: 1

Do you have any insight as why this might be happening.

Cameron

**Comment by albancho** [comment]
Hi,
It looks like an import problem... did you import dependencies in your index.html, as show in the install instructions, or in your vendor bundle if you use webpack for instance... ?

**Comment by CameronBlandy** [comment]
I don’t believe I am using webpacks (I am using a downloaded version of ESRI’s Web App Builder template). Here is my html where I put the various html2pdf components. If they should be moved please let me know.

Cameron

CAMERON BLANDY | GIS ANALYST
[COS LOGO_ email sig final]
GIS Section
13450 104 Ave, Surrey, BC,  V3T 1V8
T 604.591.4699 | F 604.598.5781 |www.surrey.ca

[Social Media Icons_email_GREEN]<http://www.surrey.ca/12392.aspx>[Social Media Icons_City Speaks_GREEN]<https://www.cityspeaks.ca/Portal/default.aspx> [Social Media Icons_Twitter_GREEN] <https://twitter.com/cityofsurrey>  [Social Media Icons_FB_GREEN] <https://www.facebook.com/TheCityofSurrey>  [Social Media Icons_YT_GREEN] <http://www.youtube.com/TheCityofSurrey>  [Social Media Icons_linkedin_GREEN] <http://www.linkedin.com/company/city-of-surrey>

Connect, Share and Engage with your City

**Comment by CameronBlandy** [comment]
Update.

When I remove the following meta tag the application successfully loads in IE
<!--<meta http-equiv="X-UA-Compatible" content="IE=Edge" />-

However it crashes at the following when creating the pdf. (html2pdf.js)
[cid:image009.png@01D35EDB.475FB620]
[cid:image002.png@01D35EDB.BDD862C0]

Any thoughts?
Cameron
CAMERON BLANDY | GIS ANALYST
[COS LOGO_ email sig final]
GIS Section
13450 104 Ave, Surrey, BC,  V3T 1V8
T 604.591.4699 | F 604.598.5781 |www.surrey.ca

[Social Media Icons_email_GREEN]<http://www.surrey.ca/12392.aspx>[Social Media Icons_City Speaks_GREEN]<https://www.cityspeaks.ca/Portal/default.aspx> [Social Media Icons_Twitter_GREEN] <https://twitter.com/cityofsurrey>  [Social Media Icons_FB_GREEN] <https://www.facebook.com/TheCityofSurrey>  [Social Media Icons_YT_GREEN] <http://www.youtube.com/TheCityofSurrey>  [Social Media Icons_linkedin_GREEN] <http://www.linkedin.com/company/city-of-surrey>

Connect, Share and Engage with your City

**Comment by albancho** [comment]
Hi,

You haven't provided the relevent html code...

**Comment by CameronBlandy** [comment]
I did attach it.

Trying again as a txt file.

CAMERON BLANDY | GIS ANALYST
[COS LOGO_ email sig final]
GIS Section
13450 104 Ave, Surrey, BC,  V3T 1V8
T 604.591.4699 | F 604.598.5781 |www.surrey.ca

[Social Media Icons_email_GREEN]<http://www.surrey.ca/12392.aspx>[Social Media Icons_City Speaks_GREEN]<https://www.cityspeaks.ca/Portal/default.aspx> [Social Media Icons_Twitter_GREEN] <https://twitter.com/cityofsurrey>  [Social Media Icons_FB_GREEN] <https://www.facebook.com/TheCityofSurrey>  [Social Media Icons_YT_GREEN] <http://www.youtube.com/TheCityofSurrey>  [Social Media Icons_linkedin_GREEN] <http://www.linkedin.com/company/city-of-surrey>

Connect, Share and Engage with your City

**Comment by eKoopmans** [comment]
@CameronBlandy, I'm really sorry I didn't get to your question earlier - I've been swamped. Did you manage to solve your issue? I'll be happy to help if it's still a problem.

My very first suggestion would be to try grabbing [the new v0.8.0 build](https://github.com/eKoopmans/html2pdf/blob/master/dist/html2pdf.bundle.min.js). That link is for the 'bundled' build, which has all the dependencies built in, and should make using it much easier. Let me know if that helps!

**Comment by CameronBlandy** [comment]
Hi Erik,

Understand that you are busy, no problem.

Tried the bundled build that you suggested and that does seem to wort much better. Only question I have is, does that include the callback branch that you created. I use that feature in my export.

Thanks again for a wonderful product.

Cameron

CAMERON BLANDY | GIS ANALYST
[COS LOGO_ email sig final]
GIS Section
13450 104 Ave, Surrey, BC,  V3T 1V8
T 604.591.4699 | F 604.598.5781 |www.surrey.ca

[Social Media Icons_email_GREEN]<http://www.surrey.ca/12392.aspx>[Social Media Icons_City Speaks_GREEN]<https://www.cityspeaks.ca/Portal/default.aspx> [Social Media Icons_Twitter_GREEN] <https://twitter.com/cityofsurrey>  [Social Media Icons_FB_GREEN] <https://www.facebook.com/TheCityofSurrey>  [Social Media Icons_YT_GREEN] <http://www.youtube.com/TheCityofSurrey>  [Social Media Icons_linkedin_GREEN] <http://www.linkedin.com/company/city-of-surrey>

Connect, Share and Engage with your City

**Comment by eKoopmans** [comment]
Good question! I've just updated the [`pdf-callback` branch](https://github.com/eKoopmans/html2pdf/tree/pdf-callback) to be in line with v0.8.0, so it should be good to go.

I'm still keeping that feature out of the main build, because I still see it as a temporary fix that I'll solve differently with the "new API". That's my next goal, now that the build process/NPM support is sorted.

**Comment by itskashi** [comment]
@eKoopmans I was wondering if you have any further update on the PDF Output feature, 
Shall I use pdf-callback branch or is there anything coming out soon. 
I need to email the generated pdf as an email attachment. Can you please advise?
_
Thanks

**Comment by eKoopmans** [comment]
Hey @itskashi, sorry to keep you hanging. Yes I'm actively working on the new API, and it's getting close to ready for testing, but if you need something that will work right now it's probably best to go with the pdf-callback branch. I'll post here when the new API is ready for testing.

**Comment by itskashi** [comment]
@eKoopmans that shall be great. As of now, I am able to resolve the problem. I had to merge the Callback branch with the latest version. The callback branch apparently has some page-break issue.

**Comment by eKoopmans** [comment]
Hi, I have just pushed a new branch, [new-api](https://github.com/eKoopmans/html2pdf/tree/new-api), which is ready for testing! [The readme](https://github.com/eKoopmans/html2pdf/tree/new-api#advanced-usage) has all the information on the new API. Please let me know if there are any problems with it - I want to make sure it's stable before merging into master!

**Comment by eKoopmans** [comment]
Hi, closing as resolved by the v0.9.0 new API.
