### ISSUE TITLE
Downloading not working for IE, but working fine for both Chrome and Firefox

### ISSUE THREAD

**Issue by manojkumarbehera** [eKoopmans/html2pdf#47]
Hi Erik Koopmans,

The download is working fine, for both Chrome and Firefox.
But in IE (Edge, 10) it is not working.can help to see this issue.
![capture](https://user-images.githubusercontent.com/11938816/32823910-d5651c0a-ca04-11e7-9221-7f9d26b5fc54.JPG)

**Comment by ml454** [comment]
for IE, need special method to download, try this

`saveFileForIE(canvas, fileName) {
    var blob = canvas.msToBlob();
    navigator.msSaveBlob(blob, fileName);
  }`

**Comment by drbeat** [comment]
try including promise for IE

https://github.com/stefanpenner/es6-promise

**Comment by eKoopmans** [comment]
Hi @drbeat and @ml454, thanks for helping answer! @manojkumarbehera, I'll be releasing a new version of html2pdf soon (next few days) with Promises bundled in, so that it should work out-of-the-box in IE.

**Comment by manojkumarbehera** [comment]
Thanks @drbeat  and @ml454.
I have resolved this issue by adding blue js.
@eKoopmans thanks for the help and the plan for the update.
Let me know once, the new version availabl.

**Comment by eKoopmans** [comment]
@manojkumarbehera the new build v0.8.0 is live! [This package](https://github.com/eKoopmans/html2pdf/blob/master/dist/html2pdf.bundle.min.js) has all the dependencies bundled in, including `es6-promise`. Let me know if you have any problems using it!
