### ISSUE TITLE
encoding utf-8

### ISSUE THREAD

**Issue by vosoghi** [eKoopmans/html2pdf#50]
How can I use it on html content with ecoding UTF-8?

**Comment by eKoopmans** [comment]
Hey @vosoghi, I'm not aware of any reason this wouldn't work with UTF-8. Can you give me an example of it not working?

**Comment by vosoghi** [comment]
Hey @eKoopmans, my html page language is persian and as you see in this picture, the letters are printer separately  and i have no idea how to fix this. if you have an idea to fix this issue, let me know please...

![qqqqq](https://user-images.githubusercontent.com/16525530/33312932-78e5bd74-d43e-11e7-8678-ee682be97f09.jpg)

**Comment by eKoopmans** [comment]
Ah okay, I see. html2pdf uses html2canvas to convert HTML to an image, and it works pretty well, but there are some issues still being sorted out. You can see that he's been tracking unicode-related issues [here](https://github.com/niklasvh/html2canvas/labels/Unicode). Unfortunately I don't have any fixes on my end.

**Comment by vosoghi** [comment]
thanks for your attention dear @eKoopmans

**Comment by eKoopmans** [comment]
Hey @vosoghi, no worries. I'm going to close this since it's an issue in html2canvas, I can't resolve it on my end.

**Comment by marwan2** [comment]
@vosoghi  did you find a solutions to Arabic string ?

**Comment by ghonchesefidi** [comment]
Using Persian fonts will solve this problem. Your font should also support UTF8
