### ISSUE TITLE
How to get file as binary using pdfCallback

### ISSUE THREAD

**Issue by MohamedFarhat5** [eKoopmans/html2pdf#51]
we try to get file as binary using pdfCallback gust updated but we face issues , 
how we can use pdfCallback , 

`it view error Type undefined `

our script 

> <script src="js/jspdf.js"></script>

> <script src="js/html2canvas.js"></script>

> <script src="js/html2pdf.min.js"></script>

> 
> <script type="text/javascript">

>     $(document).ready(function () {
>      exportIt();
>        function myCallback(pdf) {
>  			console.log('RUN')
> 		}
>         function exportIt() {
>        	 var element = document.getElementById('page-content-pdf');
> 
> 			html2pdf(element, {
> 			  margin:       0.2,
> 			  image:        { type: 'jpeg', quality: 1},
> 			  pdfCallback: myCallback,
> 			  html2canvas:  { dpi: 192, letterRendering: true ,scale: 2},
> 			  jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
> 			});
> 		}
> 
>     });
> 
> </script>

**Comment by MohamedFarhat5** [comment]
# # #

**Comment by eKoopmans** [comment]
Hi @MohamedFarhat5, you're right! Sorry, there was an error in the `pdf-callback` branch. I've fixed it now. Here's an example [working Fiddle](https://jsfiddle.net/4j0vscza/) with your code.

**Comment by MohamedFarhat5** [comment]
thank you @eKoopmans  Great effort
