### ISSUE TITLE
Does it support img <img src=''/> in html ?

### ISSUE THREAD

**Issue by danmaidesenling** [eKoopmans/html2pdf#52]
It can export html to pdf without image  the first is my code the secondimg is pdf . and the thirdis html  
![3](https://user-images.githubusercontent.com/7588416/33466031-4186c978-d686-11e7-812f-60859b6650e5.png)

 I use img 
![qq 20171201105137](https://user-images.githubusercontent.com/7588416/33465961-d5b2f744-d685-11e7-8617-d7564b0864ae.png)
![mark](https://user-images.githubusercontent.com/7588416/33465999-0a1ec4b8-d686-11e7-8fd4-fbb053496f31.png)

 in my html .

**Comment by eKoopmans** [comment]
Hi @danmaidesenling, so the image isn't showing up in the PDF? My guess is this is a problem with cross-domain images. You need to use special options in html2canvas to enable CORS and/or request the image through a proxy. There's more info on that [here](https://github.com/niklasvh/html2canvas/issues/1077#issuecomment-302484496).

**Comment by eKoopmans** [comment]
Closing - `<img>` tags are supported. Let me know if your problem hasn't been resolved!
