### ISSUE TITLE
get base64 dataURL of pdf

### ISSUE THREAD

**Issue by chinniah-a** [eKoopmans/html2pdf#54]
Is there a way to get base64URL of generated PDF using html2pdf? Moreover when I give html2pdf("element name") it automatically downloads as pdf, what I want is to store pdf for multiple elements and print as pdf at end. Thanks in advance!

**Comment by eKoopmans** [comment]
Hi @chinniah-a, yes you can get the final jsPDF object (instead of auto-saving) using the [pdf-callback branch](https://github.com/eKoopmans/html2pdf/tree/pdf-callback). More info [here](https://github.com/eKoopmans/html2pdf/issues/14#issuecomment-318798955). This branch hasn't been merged in yet because it's a workaround, I'm planning an API change that will solve this problem differently.

**Comment by chinniah-a** [comment]
Thanks @eKoopmans ! It worked

**Comment by chinniah-a** [comment]
Hi @eKoopmans , when i try to capture a html div element, only up to certain extents gets captured and rendered, rest gets cut off. This is how I have written the code
html2pdf(document.getElementById("elementId"), {
                            pdfCallback: myCallback
                          });
The overflowed content goes to second page, only some part of content is getting rendered in second page, rest is missing. Thanks in advance!

**Comment by eKoopmans** [comment]
The margin will be in whatever units you set for jsPDF. The default is mm, so 2mm will be very small.

**Comment by chinniah-a** [comment]
Hi @eKoopmans  when a textarea(which can be expanded) is a part of html, when it is extended and content is typed, I am not getting the whole expanded text area in PDF, am getting only the initial size of text area that was there before extending. why is it so?

**Comment by eKoopmans** [comment]
Possibly related to #46. If your original issue is resolved (base64 dataURL), would you mind closing this issue and opening a new issue about the textareas? It would also help if you could make a [Fiddle](https://jsfiddle.net/u6o6ne41/) that highlights the issue. Thanks!

**Comment by chinniah-a** [comment]
Sure @eKoopmans ! Thanks

**Comment by vitormc1** [comment]
@chinniah-a  can you help me with store the pdf file in my server? My plan is to send the pdf file by e-mail, but i dont know what to do with the pdf object.

My actual code:

`function myCallback(pdf) {
            console.log(pdf);
        }`


`  var element = document.getElementById('tblBoleto');
        html2pdf(element, {
            margin: [10, 5, 0, -60],
            filename: '<?= $dadosboleto["numero_documento"] . '-' . $dadosboleto["sacado_nome"] ?>.pdf',
            image: {type: 'jpeg', quality: 0.98},
            html2canvas: {dpi: 300, letterRendering: true, width: 1300, height: 1000, windowWidth: 1000, windowHeight: 1000},
            jsPDF: {unit: 'mm', format: 'a4', orientation: 'portrait'},
            pdfCallback: myCallback
        });
`

**Comment by chinniah-a** [comment]
@vitormc1 pdf.toDataURL() will give the data URL, and u can save it in the backend

**Comment by eKoopmans** [comment]
Hi, I have just pushed a new branch, [new-api](https://github.com/eKoopmans/html2pdf/tree/new-api), which is ready for testing! [The readme](https://github.com/eKoopmans/html2pdf/tree/new-api#advanced-usage) has all the information on the new API. Please let me know if there are any problems with it - I want to make sure it's stable before merging into master!

For this specific request, you can now use the `.output` method to get a datauristring, and you can reuse the PDF object to print multiple objects before saving.

**Comment by nauman555** [comment]
@chinniah-a  can you share the solution to send generated PDF as an email attachment ..

**Comment by chinniah-a** [comment]
@nauman555 
html2pdf(document.getElementById("element id"), {
pdfCallback: myCallback,
margin: 2
});

function myCallback(pdf) { console.log(pdf.toDataUrl()); }

Try by adding a callback, pdf.toDataUrl() will give the base 64 url, which you can process it

**Comment by hmusaji** [comment]
Hello eKoopmans,
i m using this .output('datauristring') but getting error like 
DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

please help
