### ISSUE TITLE
HTML Bullet point missing in PDF

### ISSUE THREAD

**Issue by KarthickTC** [eKoopmans/html2pdf#57]
Hello,
I am trying to generate PDF with rich text features with bullet points and text styles. Output PDF gets the text color and styles correctly but not the bullet points. Here my LI has inner div tags as well. 
Example : 

`<ul><li>  <div style="color:green"> Sample Text</div></li> </ul>`  

Am I missing anything in my implementation? Thanks in advance.

**Comment by eKoopmans** [comment]
Hi @KarthickTC, this issue was actually already raised in #15. html2pdf uses html2canvas to create an image from the HTML, and bullet points aren't fully supported. See #15 for more details - it's an issue in html2canvas, I can't fix it on this end.

**Comment by KarthickTC** [comment]
Sorry, I missed to see the issue #15, Thanks for the response.

**Comment by eKoopmans** [comment]
No worries @KarthickTC, sorry I can't do more to resolve it!
