### ISSUE TITLE
Overlapping characters in PDF Export

### ISSUE THREAD

**Issue by zapftho** [eKoopmans/html2pdf#59]
We are trying to implement a PDF export based on a SharePoint application page. Everything is working quite well but in IE we are seeing overlapping characters in the PDF export:

![pdfexport](https://user-images.githubusercontent.com/25010092/34044845-f5fa8f2c-e1a6-11e7-8fb7-f00cc9a0b990.png)

It seems like this is only happening in Internet Explorer & Edge. Chrome is working perfectly. However, as IE11 is our standard browser we are searching for a solution on how to fix this. Any ideas? Our configuration looks like the following:

`		html2pdf(element, {
		margin:       0,
		image:        { type: 'jpeg', quality: 0.98 },
		html2canvas:  { dpi: 192, letterRendering: true},
		jsPDF:        { orientation: 'landscape', unit:"mm", format: "a4" },
			pdfCallback:   pdfCallback
		});`

Any help would be appreciated

**Comment by eKoopmans** [comment]
Hi @zapftho, try removing `letterRendering: true` from the html2canvas options (the default is false). Other than that I'm not sure - this is an issue with the html2canvas renderer. The dev over there is working on a new release, it might fix this.

**Comment by zapftho** [comment]
@eKoopmans Had no success with removing letterRendering and also no success with actual alpha version of 1.0.0 html2Canvas... :-( I will address the issue there. Maybe someone can help there.

**Comment by eKoopmans** [comment]
Sorry to hear that, hope you're able to sort it out.

**Comment by zapftho** [comment]
Actually, it seems like the issue was related to our font size within these boxes. We have raised it from 10px to 13px and now the glitches are gone. By the way: Is 1.0.0 alpha version supported to work with your html2pdf library?

**Comment by eKoopmans** [comment]
Good question! Actually right now html2canvas v1.0.0-alpha won't work out-of-the-tin with html2pdf, because of how html2pdf calls html2canvas, but it's an easy fix. I'll try to get to that soon.

**Comment by eKoopmans** [comment]
I took care of it - html2canvas v1.0.0-alpha should now work with html2pdf. It's still not the default/bundled version... there's a few kinks that still need to be worked out. But you can use it with the unbundled version of html2pdf as described [here](https://github.com/eKoopmans/html2pdf#dependencies).

**Comment by eKoopmans** [comment]
Closing - sounds like you resolved the issue by changing font size, and possibly v1.0.0-alpha also helped solve the problem. Let me know if there's still an issue.
