### ISSUE TITLE
anyone experiencing issues downloading in Safari?

### ISSUE THREAD

**Issue by chulander** [eKoopmans/html2pdf#62]
Chrome and Firefox works fine. In Safari, data is written to the DOM but fails to trigger a download

**Comment by chulander** [comment]
please ignore, Chrome and Safari's download indicator works differently and Safari works with the latest package version.

**Comment by eKoopmans** [comment]
Glad you were able to sort this out!

**Comment by eyalCohenSC** [comment]
I'm still having problem with downloading the pdf file on Safari.

safari version: 11.0.1
html2pdf version: 0.9.0

I'm using the command:
html2pdf().from(element).set(configuration).save();

Chrome and Fire fox are working fine, but in Safari I can see the creation of the pdf logs but the file isn't downloaded.

Does this html2pdf version supports my Safari version? @eKoopmans 
What did you do to make it work? @chulander 

Thanks

**Comment by chulander** [comment]
I never had an issue downloading from safari. The issue was post-download, all the svgs on the page were scaled out of proportions.

What does your safari console say? Sounds like there’s an error there
