### ISSUE TITLE
SVG changes

### ISSUE THREAD

**Issue by chulander** [eKoopmans/html2pdf#63]
Hi, anyone experiencing CSS issues on the page after the download is triggered? I have SVGs and border's that suddenly expands after event is fired. Unfortunately I can't share a screen shot due to work data.

**Comment by eKoopmans** [comment]
Hi @chulander, I've seen other reports of that sort of behaviour resulting from html2canvas. I'll look into it when I have a chance (you can take a look on [their issue tracker](https://github.com/niklasvh/html2canvas/issues) to see if there's any solutions).

**Comment by chulander** [comment]
thanks for pointing me to the direction @eKoopmans.

**Comment by eKoopmans** [comment]
No worries, did you find a solution?

**Comment by chulander** [comment]
no I have not. From my own testing in safari, I narrowed it down to after the pdf download completes, the subsequent mouse click renders all the svg styling to be removed (i'm using css modules). if I find something, i'll let you know

**Comment by chulander** [comment]
i found the answer [here](https://github.com/cloakedninjas/html2canvas/commit/0bfd4a4e1fc92f15ec96a77e38de28729d9548e9). Now the question is how to implement this in my project. I may either create a new repo forking all h2ml2canvas and this repo or not sure yet.

**Comment by chulander** [comment]
@eKoopmans , I created a [PR](https://github.com/eKoopmans/html2canvas/pull/2/files) to your forked html2canvas with the solution from @cloakedninjas

**Comment by eKoopmans** [comment]
Hi @chulander, I've followed up on the PR, thanks.

**Comment by chulander** [comment]
thanks for updating this repo @eKoopmans. I'm working on the bug / demo for html2canvas. let you know when i finish it.

**Comment by chulander** [comment]
hi @eKoopmans , i just saw your message on the (html2canvas#1346)[https://github.com/niklasvh/html2canvas/issues/1346]

**Comment by eKoopmans** [comment]
Yep that's the idea. We'll figure something out though.
