### ISSUE TITLE
Problems with download on iPhone "PWA"

### ISSUE THREAD

**Issue by renatho** [eKoopmans/html2pdf#66]
I have an app with the meta bellow to works like a PWA when the user adds it to his homescreen:
<meta name="apple-mobile-web-app-capable" content="yes">

But... When I use the html2pdf, this open the PDF in a fullscreen page and the user can't navigate or go back. It stays prevented from navigate.

Any ideas to solve this problem?

Attached a screenshot from my ios simulator:
![ios](https://user-images.githubusercontent.com/876340/34448307-2e65c8ae-ecd3-11e7-9705-0b883f7a940a.png)

**Comment by eKoopmans** [comment]
Hi @renatho, good question! I don't have an iPhone to test on. html2pdf uses jsPDF to generate the PDF - you could look through the [issue tracker there](https://github.com/MrRio/jsPDF/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ios) to see if there's any solutions.

Specifically, html2pdf uses `pdf.save()` at the end to finish the PDF and provide the file for downloading. You could try using the `jspdf-callback` branch of html2pdf, described [here](https://github.com/eKoopmans/html2pdf/issues/54#issuecomment-349207273), which will give you the jsPDF object *before* save is called. Then you could see if a different option other than `.save()` works better on iOS.

**Comment by renatho** [comment]
@eKoopmans Thanks!

**Comment by eKoopmans** [comment]
Hi @renatho, out of curiosity, did you find a working solution for iPhone?

**Comment by renatho** [comment]
Hi @eKoopmans!
No =\
We solved by generating the PDF on server-side. The future solution that we will work is to share the PDF through google drive, email and other ways instead of to download.

**Comment by eKoopmans** [comment]
Hey @renatho, that sounds like a good way to go. Server-side options are a lot more robust right now - [wkhtmltopdf](https://wkhtmltopdf.org/) is a great tool. Sorry html2pdf didn't work out!

**Comment by JoakFlores** [comment]
Hi evry bady

To download PDF file on Android PWA, how can I do?

**Comment by hooliapps** [comment]
Hello,

I did the following code to convert the HTML content then Share it (on iOS)


// Convert HTML to PDF, then share it
var pdfOptions = {
	margin: 0.5,
	jsPDF: {
		unit: 'in',
		format: 'A4',
		orientation: printOrientation
	}
};
    
html2pdf().set(pdfOptions).from(html).toPdf().output('datauristring').then(function(pdfAsString) {
	// Share it
	var shareOptions = {
		files: ['df:FILENAME.pdf;'+pdfAsString],
		chooserTitle: 'TITLE'
	};
	
	window.plugins.socialsharing.shareWithOptions(
		shareOptions,
		function(res) {
		},
		function(err) {		}
	);
});
