### ISSUE TITLE
HTML Font Support

### ISSUE THREAD

**Issue by ajayppeter** [eKoopmans/html2pdf#8]
Hi,

Is it possible to add font support which are used in HTML ? like font icons, open sans, etc

Regards,
Ajay

**Comment by eKoopmans** [comment]
Hi @ajayppeter, font support is determined by [html2canvas](https://github.com/niklasvh/html2canvas), which is the dependency responsible for actually converting the HTML into an image. In my experience it actually supports a number of fonts - for instance, I've successfully used it with Google's [material font icons](https://material.io/icons/). I'd recommend exploring the issue tracker there for more info about supported fonts.
