### ISSUE TITLE
Get error: Uncaught Missing source element or string.

### ISSUE THREAD

**Issue by ChristophClaus** [eKoopmans/html2pdf#84]
I have created a minimalist html page and get the error: "Uncaught Missing source element or string." I don´t know, what I´ve done wrong... Please help! Thanks!

```
<script src="https://rawgit.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.min.js"></script>
<script>
	var element = document.getElementById('element-to-print');
	html2pdf(element);
</script>
<div id="element-to-print">TEST</div>
```

**Comment by eKoopmans** [comment]
Hi @ChristophClaus, everything looks good except your script tag is *before* your div, which means that when the script runs the div doesn't exist yet! Put the script at the very end of your body, or use `window.onload` to delay execution of your script until the whole page is loaded.

**Comment by ChristophClaus** [comment]
Perfect! Thank you!
