### ISSUE TITLE
Add option to just return Blob instead of downloading file

### ISSUE THREAD

**Issue by markb-trustifi** [eKoopmans/html2pdf#89]
P.S. I see there are branches "new-api" and "pdf-callback". When they are going to be merged with master?

**Comment by morganzysman** [comment]
I also very interested in this feature

**Comment by yporret** [comment]
same... it would really help

**Comment by morganzysman** [comment]
This might help you guys
  var worker = html2pdf().from(element).set(options).then(function () {
                  setTimeout(function () {
                      worker.save();
                  },2000);
              });

**Comment by morganzysman** [comment]
My mistake, render only seems to be triggered when saved is called.

I want to automatically, generate the PDF and allow user to download it when rendered is over.
I'm doing this because, rendering can take up to several minutes, and I don't want to have the user waiting this long.

If anyone has any hint.

Regards,

Morgan

**Comment by kevinpiac** [comment]
@morganzysman @yporret @markb-trustifi 

Disclaimer: I personally use the new-api branch, which is still in test mode. Did not checked for other branches.

Hey guys, I had the same issue. By diving a little bit into the code it appears that the `output` method registered for the [worker object ](https://github.com/eKoopmans/html2pdf/blob/new-api/src/worker.js)supports pdfjs type as argument:
- arraybuffer
- blob
- bloburi
- datauristring
- datauri 

Usage example with outputPdf method (which is a wrapper for output with 'pdf' as src value) :
```
const elem = document.getElementById('html');
html2pdf().from(elem).outputPdf('arrayBuffer').then((blob) => {
 // handle your blob here...
});
```

- Implemented [here](https://rawgit.com/MrRio/jsPDF/master/docs/jspdf.js.html#line992) in the source code
- Also see jspdf types in jspdf source [here](https://rawgit.com/MrRio/jsPDF/master/docs/jspdf.js.html#line992) for more info about what each type is doing

**Comment by bencleary** [comment]
@kevinpiac works great, just one thing the type arg you passed in your example should be arraybuffer not arrayBuffer just a small typo change if anyone else comes looking for this..

**Comment by kevinpiac** [comment]
@bencleary oh sorry, I edited the list but not the code snippet, my bad! Thanks for reporting this mistake. I changed the snippet.

**Comment by markb-trustifi** [comment]
I found it in version:
"html2pdf.js": "0.9.0",
"jspdf": "1.4.1"
