### ISSUE TITLE
Nodelist forEach() is NOT supported in any version of IE/Edge

### ISSUE THREAD

**Issue by Colinh84** [eKoopmans/html2pdf#9]
You are using a forEach() loop on a nodelist in the pagebreaks section:

```JS
// Enable page-breaks.
    var pageBreaks = source.querySelectorAll('.html2pdf__page-break');
    var pxPageHeight = pageSize.inner.height * pageSize.k / 72 * 96;
    pageBreaks.forEach(function(el) {
      el.style.display = 'block';
      var clientRect = el.getBoundingClientRect();
      el.style.height = pxPageHeight - (clientRect.top % pxPageHeight) + 'px';
    }, this);
```

This is not part of any JS standard, and not supported by any MS browser causing a console error and failure of pdf generation.

https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

I got around this using a polyfill in my code:

```JS
(function () {
    if ( typeof NodeList.prototype.forEach === "function" ) return false;
    NodeList.prototype.forEach = Array.prototype.forEach;
})();
```

But this isn't really a good solution to have to put polyfills into my own code for this problem..

**Comment by eKoopmans** [comment]
Thanks @Colinh84! You're right, I had tried to be careful about that before but I missed this one. I'll fix that up.
